//! Catálogo de limpieza de **macOS**.
//!
//! Las rutas están tomadas de `rules/darwin/*.json` de [Kudu](https://github.com/adventdevinc/kudu)
//! (MIT), que es quien mantiene esa lista comprobada; los textos están en español
//! porque toda la interfaz lo está. Aquí NO se inventa ninguna ruta.
//!
//! Kudu escribe sus rutas con sus propias variables; aquí se traducen a las
//! nuestras cuando significan lo mismo: su `${APP_SUPPORT}` es nuestro `${CONFIG}`
//! (`~/Library/Application Support`) y su `${CACHES}` es nuestro `${CACHE}`
//! (`~/Library/Caches`). Su `childSubdir` (limpiar solo una subcarpeta) se traduce
//! en un comodín en la ruta (`Perfiles/*/cache2`). Cuando Kudu marca `minAgeDays`
//! se usa `.con_dias_como(n)`; cuando marca `needsAdmin`, `.con_root_como("...")`
//! con el comando real de macOS (la app NO lo lanza: enseña el comando) y cuando
//! marca `cacheReset`, `.con_reinicio_cache()` (caché de rendimiento: se puede
//! borrar, pero la primera vez todo va más lento).
//!
//! Los navegadores basados en Chromium los describe Kudu como un par
//! `base`/`cache` y limpia subcarpetas concretas dentro de cada perfil; aquí se
//! limpia el directorio de caché completo, `${CACHE}/<navegador>`, que es lo que
//! hay bajo `Caches` y por definición se puede tirar (macOS lo purga solo). Los
//! perfiles, el historial y las contraseñas viven en `${CONFIG}`, no ahí.
//!
//! Variables disponibles (las resuelve `expandir`, en `limpieza.rs`):
//! `${HOME}`, `${CACHE}` (`~/Library/Caches`), `${CONFIG}` (`~/Library/Application
//! Support`), `${LIBRARY}` (`~/Library`), `${LOCAL_SHARE}`, `${TEMP}`.
//!
//! La sección `privacidad` son huellas de TU actividad (historiales de shell,
//! recientes, listas de descargas): NO se regeneran solas, van marcadas con
//! `.marcar_traza()` y solo se limpian si se pide esa categoría.
use super::{regla, Regla, TipoRegla};

pub const REGLAS: &[Regla] = &[
    /* ── Sistema ──────────────────────────────────────────────────────────── */
    regla(
        "macos-temp-usuario",
        "sistema",
        "Temporales del usuario",
        "Ficheros temporales de tus aplicaciones y de tu sesión; los de menos de un día se conservan porque pueden estar en uso",
        &["${TEMP}"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "macos-temp-sistema",
        "sistema",
        "Temporales del sistema",
        "Temporales compartidos de todo el sistema; macOS ya los vacía al reiniciar",
        &["/private/tmp"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-logs-usuario",
        "sistema",
        "Registros de usuario",
        "Registros de las aplicaciones de tu sesión de más de una semana; no toca los del sistema",
        &["${LIBRARY}/Logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "macos-logs-sistema",
        "sistema",
        "Registros del sistema",
        "Registros de los servicios de macOS y de las aplicaciones instaladas (necesita permisos de administrador)",
        &["/Library/Logs"],
        TipoRegla::Contenido,
    )
    .con_root_como("sudo rm -rf /Library/Logs/*"),
    regla(
        "macos-informes-usuario",
        "sistema",
        "Informes de fallo",
        "Informes que macOS guarda cuando una aplicación tuya se cierra mal o se cuelga",
        &["${LIBRARY}/Logs/DiagnosticReports"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-informes-sistema",
        "sistema",
        "Informes de fallo del sistema",
        "Informes de fallo, cuelgue y bloqueo de los servicios del sistema y del núcleo (necesita permisos de administrador)",
        &["/Library/Logs/DiagnosticReports"],
        TipoRegla::Contenido,
    )
    .con_root_como("sudo rm -rf /Library/Logs/DiagnosticReports/*"),
    regla(
        "macos-papelera",
        "sistema",
        "Papelera",
        "Lo que hay en la papelera. Es lo ÚNICO que libera de verdad el espacio de lo que se manda allí",
        &["${HOME}/.Trash"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-miniaturas",
        "sistema",
        "Miniaturas del Finder",
        "Miniaturas que el Finder guarda para las vistas previas; se rehacen al abrir las carpetas",
        &["${CACHE}/com.apple.QuickLook.thumbnailcache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-fuentes-ats",
        "sistema",
        "Caché de fuentes",
        "Caché de renderizado de fuentes de Apple Type Services (necesita permisos de administrador); se rehace sola",
        &["/Library/Caches/com.apple.ATS"],
        TipoRegla::Contenido,
    )
    .con_root_como("sudo rm -rf /Library/Caches/com.apple.ATS/*"),
    regla(
        "macos-estado-apps",
        "sistema",
        "Estado guardado de las aplicaciones",
        "Posición de ventanas y estado que las aplicaciones guardan para reabrirse tal cual; se pierde el «Reanudar» al reabrir",
        &["${LIBRARY}/Saved Application State"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-caches-contenedores",
        "sistema",
        "Cachés de aplicaciones en sandbox",
        "Cachés de las aplicaciones del App Store y notarizadas, cada una dentro de su contenedor; se regeneran solas",
        &["${LIBRARY}/Containers/*/Data/Library/Caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-xcode-deriveddata",
        "sistema",
        "Xcode (DerivedData)",
        "Productos de compilación, índices y ficheros intermedios de Xcode; se rehacen en la siguiente compilación",
        &["${LIBRARY}/Developer/Xcode/DerivedData"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-coresimulator",
        "sistema",
        "CoreSimulator (cachés)",
        "Datos en caché de los simuladores de iOS, tvOS y watchOS; se regeneran al usarlos",
        &["${LIBRARY}/Developer/CoreSimulator/Caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-xcode-dispositivos",
        "sistema",
        "Xcode (dispositivos)",
        "Símbolos de depuración y registros que Xcode copia de los dispositivos conectados; se vuelven a copiar la próxima vez",
        &[
            "${LIBRARY}/Developer/Xcode/iOS DeviceSupport",
            "${LIBRARY}/Developer/Xcode/watchOS DeviceSupport",
            "${LIBRARY}/Developer/Xcode/tvOS DeviceSupport",
            "${LIBRARY}/Developer/Xcode/iOS Device Logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-herramientas-apple",
        "sistema",
        "Herramientas de desarrollo de Apple",
        "Descargas de componentes y documentación de Xcode, del gestor de paquetes de Swift y de Instruments; se vuelven a bajar",
        &["${CACHE}/com.apple.dt.Xcode", "${CACHE}/org.swift.swiftpm", "${CACHE}/com.apple.DeveloperTools"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-iconos-sistema",
        "sistema",
        "Caché de iconos del sistema",
        "Iconos de aplicaciones en caché de todo el sistema (necesita permisos de administrador); se rehacen solos",
        &["/Library/Caches/com.apple.iconservices.store"],
        TipoRegla::Contenido,
    )
    .con_root_como("sudo rm -rf /Library/Caches/com.apple.iconservices.store/*"),
    regla(
        "macos-asl",
        "sistema",
        "Registros ASL heredados",
        "Archivos del antiguo registro Apple System Log, sustituido por el registro unificado en macOS modernos (necesita permisos de administrador)",
        &["/private/var/log/asl"],
        TipoRegla::Contenido,
    )
    .con_root_como("sudo rm -rf /private/var/log/asl/*"),
    regla(
        "macos-url-session",
        "sistema",
        "Caché de sesiones de red",
        "Respuestas HTTP y HTTPS en caché de las peticiones de red del sistema; se vuelven a pedir",
        &["${LIBRARY}/Caches/com.apple.nsurlsessiond"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-cache-delete",
        "sistema",
        "Registros de gestión de caché",
        "Registros del servicio de macOS que libera caché automáticamente",
        &["${LIBRARY}/Caches/com.apple.CacheDelete"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-fuentes-registry",
        "sistema",
        "Caché del registro de fuentes",
        "Ficheros de la caché del registro de fuentes; se rehacen cuando hacen falta",
        &["${CACHE}/com.apple.FontRegistry"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-software-ios",
        "sistema",
        "Imágenes de software de iPhone y iPad",
        "Imágenes de restauración (IPSW) de iPhone y iPad descargadas; el Finder las vuelve a bajar si hacen falta",
        &["${LIBRARY}/iTunes/iPhone Software Updates", "${LIBRARY}/iTunes/iPad Software Updates"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-diagnosticos-statuskit",
        "sistema",
        "Caché de diagnósticos",
        "Datos en caché de los diagnósticos y los informes del sistema de macOS",
        &["${LIBRARY}/Caches/com.apple.diagnosticsextensions.statuskit"],
        TipoRegla::Contenido,
    ),

    /* ── Navegadores ──────────────────────────────────────────────────────── */
    regla(
        "macos-safari",
        "navegadores",
        "Safari",
        "Caché web de Safari; conserva historial, marcadores y contraseñas",
        &["${CACHE}/com.apple.Safari"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-chrome",
        "navegadores",
        "Google Chrome",
        "Caché de Chrome; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Google/Chrome"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-edge",
        "navegadores",
        "Microsoft Edge",
        "Caché de Edge; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Microsoft Edge"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-firefox",
        "navegadores",
        "Firefox",
        "Caché web de Firefox (todos sus perfiles)",
        &["${CACHE}/Firefox"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-brave",
        "navegadores",
        "Brave",
        "Caché de Brave; conserva perfiles, historial y contraseñas",
        &["${CACHE}/BraveSoftware/Brave-Browser"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-opera",
        "navegadores",
        "Opera",
        "Caché de Opera y Opera GX; conserva perfiles, historial y contraseñas",
        &["${CACHE}/com.operasoftware.Opera", "${CACHE}/com.operasoftware.OperaGX"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-vivaldi",
        "navegadores",
        "Vivaldi",
        "Caché de Vivaldi; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Vivaldi"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-arc",
        "navegadores",
        "Arc",
        "Caché de Arc; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Arc/User Data"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-thorium",
        "navegadores",
        "Thorium",
        "Caché de Thorium; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Thorium"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-supermium",
        "navegadores",
        "Supermium",
        "Caché de Supermium; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Supermium"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-chromium",
        "navegadores",
        "Chromium",
        "Caché de Chromium; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Chromium"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-helium",
        "navegadores",
        "Helium",
        "Caché de Helium; conserva perfiles, historial y contraseñas",
        &["${CACHE}/net.imput.helium"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-cromite",
        "navegadores",
        "Cromite",
        "Caché de Cromite; conserva perfiles, historial y contraseñas",
        &["${CACHE}/Cromite"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-catsxp",
        "navegadores",
        "CatsXP",
        "Caché de CatsXP; conserva perfiles, historial y contraseñas",
        &["${CACHE}/ArcSoft/CatsXP"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-navegadores-firefox",
        "navegadores",
        "Navegadores basados en Firefox",
        "Caché web de LibreWolf, Waterfox, Floorp y Zen; conserva perfiles, historial y contraseñas",
        &["${CACHE}/LibreWolf", "${CACHE}/Waterfox", "${CACHE}/Floorp", "${CACHE}/Zen"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-thunderbird",
        "navegadores",
        "Thunderbird",
        "Caché web de cada perfil de Thunderbird; conserva el correo y las cuentas",
        &["${CACHE}/Thunderbird/Profiles/*/cache2"],
        TipoRegla::Contenido,
    ),

    /* ── Aplicaciones y desarrollo ────────────────────────────────────────── */
    regla(
        "macos-npm",
        "apps",
        "npm",
        "Paquetes y metadatos que descarga npm; se vuelven a bajar",
        &["${HOME}/.npm/_cacache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-yarn",
        "apps",
        "Yarn",
        "Paquetes descargados por Yarn; `yarn cache clean` haría lo mismo",
        &["${CACHE}/Yarn"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-pnpm",
        "apps",
        "pnpm (almacén)",
        "pnpm limpia su almacén mejor con su comando: borra lo que ya no referencia ningún proyecto y conserva el resto",
        &["${LIBRARY}/pnpm/store"],
        TipoRegla::Comando,
    )
    .con_comando_como("pnpm store prune"),
    regla(
        "macos-pip",
        "apps",
        "pip y Pipenv",
        "Ruedas y distribuciones descargadas por pip y Pipenv; se vuelven a bajar",
        &["${CACHE}/pip", "${CACHE}/pipenv"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-uv",
        "apps",
        "uv (caché)",
        "uv limpia su caché mejor con su comando: conserva lo que sigue en uso",
        &["${HOME}"],
        TipoRegla::Comando,
    )
    .con_comando_como("uv cache prune"),
    regla(
        "macos-bun",
        "apps",
        "Bun",
        "Paquetes descargados por Bun",
        &["${HOME}/.bun/install/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-cargo",
        "apps",
        "Cargo",
        "Ficheros .crate descargados, fuentes extraídas y checkouts de git; se rehacen al compilar",
        &["${HOME}/.cargo/registry/cache", "${HOME}/.cargo/registry/src", "${HOME}/.cargo/git/checkouts"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-go",
        "apps",
        "Go",
        "Módulos descargados y caché del compilador de Go; se rehacen en la siguiente compilación",
        &["${HOME}/go/pkg/mod/cache", "${CACHE}/go-build"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-gradle",
        "apps",
        "Gradle",
        "Cachés de compilación y registros del demonio de Gradle",
        &["${HOME}/.gradle/caches", "${HOME}/.gradle/daemon"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-composer",
        "apps",
        "Composer",
        "Paquetes PHP descargados por Composer",
        &["${CACHE}/composer"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-conda",
        "apps",
        "Conda",
        "Paquetes descargados por Conda; `conda clean --packages` haría lo mismo",
        &["${HOME}/anaconda3/pkgs", "${HOME}/miniconda3/pkgs", "${HOME}/.conda/pkgs"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-homebrew",
        "apps",
        "Homebrew",
        "Botellas y fuentes descargadas por Homebrew y sus registros de compilación",
        &["${CACHE}/Homebrew", "${LIBRARY}/Logs/Homebrew"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-vscode",
        "apps",
        "Visual Studio Code",
        "Caché web, de código compilado y de GPU de VS Code, paquetes de extensiones descargados y registros; conserva los ajustes y las extensiones instaladas",
        &[
            "${CONFIG}/Code/Cache/Cache_Data",
            "${CONFIG}/Code/Code Cache",
            "${CONFIG}/Code/GPUCache",
            "${CONFIG}/Code/logs",
            "${CONFIG}/Code/CachedExtensionVSIXs",
            "${CONFIG}/Code/CachedData",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-jetbrains",
        "apps",
        "JetBrains",
        "Cachés de los IDE de JetBrains (IntelliJ, PyCharm, WebStorm…); se rehacen al reiniciar",
        &["${CACHE}/JetBrains"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-android-studio",
        "apps",
        "Android Studio",
        "Cachés por versión de Android Studio; no toca los índices ni el historial local de los proyectos",
        &["${CACHE}/Google/*/caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-docker-desktop",
        "apps",
        "Docker Desktop",
        "Datos en caché de Docker Desktop; se rehacen solos",
        &["${CACHE}/com.docker.docker"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-docker-build",
        "apps",
        "Docker (caché de compilación)",
        "Docker limpia su caché de compilación mejor con su comando (no toca contenedores, volúmenes ni imágenes)",
        &["${HOME}"],
        TipoRegla::Comando,
    )
    .con_comando_como("docker builder prune"),
    regla(
        "macos-electron",
        "apps",
        "Electron",
        "Runtime de Electron y descargas de electron-builder de más de una semana; se vuelven a bajar",
        &["${CACHE}/electron", "${CACHE}/electron-builder"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "macos-discord",
        "apps",
        "Discord",
        "Caché web, de código compilado y de GPU de Discord; conserva la sesión y los ajustes",
        &["${CONFIG}/discord/Cache/Cache_Data", "${CONFIG}/discord/Code Cache", "${CONFIG}/discord/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-slack",
        "apps",
        "Slack",
        "Caché web, de código compilado y de GPU de Slack; conserva la sesión y los ajustes",
        &["${CONFIG}/Slack/Cache/Cache_Data", "${CONFIG}/Slack/Code Cache", "${CONFIG}/Slack/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-teams",
        "apps",
        "Microsoft Teams",
        "Contenido web en caché de Microsoft Teams; conserva la cuenta y las conversaciones",
        &["${CONFIG}/Microsoft Teams/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-spotify",
        "apps",
        "Spotify",
        "Datos de streaming en caché de Spotify; conserva la cuenta, las listas y las descargas para uso sin conexión",
        &["${CACHE}/com.spotify.client"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-zoom",
        "apps",
        "Zoom",
        "Caché, de GPU y registros de Zoom; conserva la cuenta y los ajustes",
        &["${CONFIG}/zoom.us/data/Cache", "${CONFIG}/zoom.us/data/GPUCache", "${CONFIG}/zoom.us/data/logs", "${LIBRARY}/Logs/zoom.us"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-telegram",
        "apps",
        "Telegram",
        "Datos de usuario en caché y emojis de Telegram; conserva la cuenta y los chats",
        &["${CONFIG}/Telegram Desktop/tdata/user_data", "${CONFIG}/Telegram Desktop/tdata/emoji"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-obs",
        "apps",
        "OBS Studio",
        "Registros y datos del generador de perfiles de OBS Studio",
        &["${CONFIG}/obs-studio/logs", "${CONFIG}/obs-studio/profiler_data"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-adobe",
        "apps",
        "Adobe Creative Cloud",
        "Caché de Adobe y caché multimedia compartida de Premiere, After Effects y compañía; se rehace al reabrir los proyectos",
        &["${CACHE}/Adobe", "${CONFIG}/Adobe/Common/Media Cache Files", "${CONFIG}/Adobe/Common/Media Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-maven",
        "apps",
        "Maven",
        "Repositorio local de artefactos de Maven; se vuelven a bajar",
        &["${HOME}/.m2/repository"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-signal",
        "apps",
        "Signal",
        "Caché web, de código compilado y de GPU de Signal; conserva los mensajes y la cuenta",
        &["${CONFIG}/Signal/Cache/Cache_Data", "${CONFIG}/Signal/Code Cache", "${CONFIG}/Signal/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-postman",
        "apps",
        "Postman",
        "Caché web, de código compilado y de GPU de Postman; conserva las colecciones y el entorno",
        &["${CONFIG}/Postman/Cache/Cache_Data", "${CONFIG}/Postman/Code Cache", "${CONFIG}/Postman/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-figma",
        "apps",
        "Figma",
        "Caché web, de código compilado y de GPU de Figma; conserva la cuenta y los ficheros",
        &["${CONFIG}/Figma/Cache/Cache_Data", "${CONFIG}/Figma/Code Cache", "${CONFIG}/Figma/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-github-desktop",
        "apps",
        "GitHub Desktop",
        "Caché web, de código compilado y de GPU de GitHub Desktop; conserva los repositorios y las credenciales",
        &["${CONFIG}/GitHub Desktop/Cache/Cache_Data", "${CONFIG}/GitHub Desktop/Code Cache", "${CONFIG}/GitHub Desktop/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-vlc",
        "apps",
        "VLC",
        "Carátulas y miniaturas en caché de VLC",
        &["${CACHE}/org.videolan.vlc"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-gimp",
        "apps",
        "GIMP",
        "Caché de renderizado y de recursos de GIMP en sus versiones 2.10, 2.99 y 3.0",
        &["${CACHE}/org.gimp.gimp-2.10", "${CACHE}/org.gimp.gimp-2.99", "${CACHE}/org.gimp.gimp-3.0"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-blender",
        "apps",
        "Blender",
        "Caché de miniaturas y scripts de Blender por versión",
        &["${CONFIG}/Blender/*/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-libreoffice",
        "apps",
        "LibreOffice",
        "Datos en caché de LibreOffice, incluidas las miniaturas de extensiones",
        &["${CACHE}/LibreOffice"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-teamviewer",
        "apps",
        "TeamViewer",
        "Caché de TeamViewer y registros de sesión",
        &["${CACHE}/com.teamviewer.TeamViewer", "${LIBRARY}/Logs/TeamViewer"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-google-earth",
        "apps",
        "Google Earth",
        "Mosaicos de imágenes de satélite en caché de Google Earth; se vuelven a descargar",
        &["${CACHE}/com.google.GoogleEarthPro", "${CACHE}/com.google.GoogleEarth"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-inkscape",
        "apps",
        "Inkscape",
        "Caché de fuentes y de renderizado de Inkscape",
        &["${CACHE}/org.inkscape.Inkscape"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-krita",
        "apps",
        "Krita",
        "Caché de recursos y de renderizado de Krita",
        &["${CACHE}/krita"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-filezilla",
        "apps",
        "FileZilla",
        "Caché de listados de directorios de FileZilla",
        &["${CACHE}/FileZilla"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-transmission",
        "apps",
        "Transmission",
        "Caché del cliente BitTorrent Transmission",
        &["${CACHE}/org.m0k.transmission"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-notion",
        "apps",
        "Notion",
        "Caché web, de código compilado y de GPU de Notion; conserva las páginas y la sesión",
        &["${CONFIG}/Notion/Cache/Cache_Data", "${CONFIG}/Notion/Code Cache", "${CONFIG}/Notion/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-obsidian",
        "apps",
        "Obsidian",
        "Caché web, de código compilado y de GPU de Obsidian; conserva las notas y los ajustes",
        &["${CONFIG}/obsidian/Cache/Cache_Data", "${CONFIG}/obsidian/Code Cache", "${CONFIG}/obsidian/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-whatsapp",
        "apps",
        "WhatsApp",
        "Caché web de WhatsApp Desktop; conserva los chats y la cuenta",
        &["${CONFIG}/WhatsApp/Cache/Cache_Data"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-bitwarden",
        "apps",
        "Bitwarden",
        "Caché web, de código compilado y de GPU de Bitwarden; conserva la bóveda y la cuenta",
        &["${CONFIG}/Bitwarden/Cache/Cache_Data", "${CONFIG}/Bitwarden/Code Cache", "${CONFIG}/Bitwarden/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-ruby-gems",
        "apps",
        "Gemas de Ruby",
        "Ficheros .gem descargados; se vuelven a bajar cuando hacen falta",
        &["${HOME}/.gem/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-cocoapods",
        "apps",
        "CocoaPods",
        "Descargas de CocoaPods; `pod cache clean --all` haría lo mismo",
        &["${CACHE}/CocoaPods"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-deno",
        "apps",
        "Deno",
        "Caché de módulos de Deno; se vuelven a bajar",
        &["${CACHE}/deno"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-sublime",
        "apps",
        "Sublime Text",
        "Caché de índices y recursos de Sublime Text",
        &["${CACHE}/com.sublimetext.4"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-termius",
        "apps",
        "Termius",
        "Caché web, de código compilado y de GPU de Termius; conserva los hosts y las credenciales",
        &["${CONFIG}/Termius/Cache/Cache_Data", "${CONFIG}/Termius/Code Cache", "${CONFIG}/Termius/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-ledger-live",
        "apps",
        "Ledger Live",
        "Caché web, de código compilado y de GPU de Ledger Live; conserva la cuenta",
        &["${CONFIG}/Ledger Live/Cache/Cache_Data", "${CONFIG}/Ledger Live/Code Cache", "${CONFIG}/Ledger Live/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-node-gyp",
        "apps",
        "node-gyp",
        "Cabeceras de Node.js que descarga node-gyp para compilar módulos nativos",
        &["${HOME}/.node-gyp"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-kodi",
        "apps",
        "Kodi",
        "Caché y miniaturas de Kodi; pueden ocupar varios GB y se rehacen cuando hacen falta",
        &["${CACHE}/org.xbmc.kodi", "${CONFIG}/Kodi/userdata/Thumbnails"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-qbittorrent",
        "apps",
        "qBittorrent",
        "Registros de qBittorrent",
        &["${CONFIG}/qBittorrent/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-handbrake",
        "apps",
        "HandBrake",
        "Registros de codificación de HandBrake (ubicación normal, en contenedor y caché)",
        &[
            "${CONFIG}/HandBrake/EncodeLogs",
            "${HOME}/Library/Containers/fr.handbrake.HandBrake/Data/Library/Application Support/HandBrake/EncodeLogs",
            "${CACHE}/fr.handbrake.HandBrake",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-ccache",
        "apps",
        "ccache",
        "Caché de compilación de C/C++; la próxima compilación tarda algo más",
        &["${CACHE}/ccache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-sccache",
        "apps",
        "sccache",
        "Caché de compilación compartida de Rust y C/C++; la próxima compilación tarda algo más",
        &["${CACHE}/Mozilla.sccache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-java",
        "apps",
        "Java",
        "Caché de descargas de Java Web Start y de applets (tecnología retirada)",
        &["${CONFIG}/Oracle/Java/Deployment/cache", "${CACHE}/Java"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-hyper",
        "apps",
        "Hyper",
        "Caché web, de código compilado y de GPU de Hyper; conserva la configuración",
        &["${CONFIG}/Hyper/Cache/Cache_Data", "${CONFIG}/Hyper/Code Cache", "${CONFIG}/Hyper/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-linear",
        "apps",
        "Linear",
        "Caché web, de código compilado y de GPU de Linear; conserva la sesión",
        &["${CONFIG}/Linear/Cache/Cache_Data", "${CONFIG}/Linear/Code Cache", "${CONFIG}/Linear/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-todoist",
        "apps",
        "Todoist",
        "Caché web, de código compilado y de GPU de Todoist; conserva las tareas y la cuenta",
        &["${CONFIG}/Todoist/Cache/Cache_Data", "${CONFIG}/Todoist/Code Cache", "${CONFIG}/Todoist/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-loom",
        "apps",
        "Loom",
        "Caché web, de código compilado y de GPU de Loom; conserva los vídeos y la cuenta",
        &["${CONFIG}/Loom/Cache/Cache_Data", "${CONFIG}/Loom/Code Cache", "${CONFIG}/Loom/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-1password",
        "apps",
        "1Password",
        "Caché web, de código compilado y de GPU de 1Password; conserva la bóveda y la cuenta",
        &["${CONFIG}/1Password/Cache/Cache_Data", "${CONFIG}/1Password/Code Cache", "${CONFIG}/1Password/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-zed",
        "apps",
        "Zed",
        "Caché y registros del editor Zed; se rehacen solos",
        &["${CACHE}/dev.zed.Zed", "${LIBRARY}/Logs/Zed"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-aws-cli",
        "apps",
        "AWS CLI",
        "Respuestas de API en caché de AWS CLI; se vuelven a pedir",
        &["${HOME}/.aws/cli/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-gcloud",
        "apps",
        "Google Cloud CLI",
        "Registros y datos en caché de la CLI de Google Cloud",
        &["${HOME}/.config/gcloud/logs", "${HOME}/.config/gcloud/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-vscode-insiders",
        "apps",
        "VS Code Insiders",
        "Caché web, de código compilado y de GPU de VS Code Insiders, paquetes de extensiones descargados y registros; conserva los ajustes y las extensiones",
        &[
            "${CONFIG}/Code - Insiders/Cache/Cache_Data",
            "${CONFIG}/Code - Insiders/Code Cache",
            "${CONFIG}/Code - Insiders/GPUCache",
            "${CONFIG}/Code - Insiders/CachedData",
            "${CONFIG}/Code - Insiders/CachedExtensionVSIXs",
            "${CONFIG}/Code - Insiders/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-vscodium",
        "apps",
        "VSCodium",
        "Caché web, de código compilado y de GPU de VSCodium, paquetes de extensiones descargados y registros; conserva los ajustes y las extensiones",
        &[
            "${CONFIG}/VSCodium/Cache/Cache_Data",
            "${CONFIG}/VSCodium/Code Cache",
            "${CONFIG}/VSCodium/GPUCache",
            "${CONFIG}/VSCodium/CachedData",
            "${CONFIG}/VSCodium/CachedExtensionVSIXs",
            "${CONFIG}/VSCodium/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-discord-ptb",
        "apps",
        "Discord PTB",
        "Caché web, de código compilado y de GPU de Discord PTB; conserva la sesión y los ajustes",
        &["${CONFIG}/discordptb/Cache/Cache_Data", "${CONFIG}/discordptb/Code Cache", "${CONFIG}/discordptb/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-discord-canary",
        "apps",
        "Discord Canary",
        "Caché web, de código compilado y de GPU de Discord Canary; conserva la sesión y los ajustes",
        &["${CONFIG}/discordcanary/Cache/Cache_Data", "${CONFIG}/discordcanary/Code Cache", "${CONFIG}/discordcanary/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-typescript",
        "apps",
        "TypeScript",
        "Definiciones que el servidor de TypeScript descarga para proyectos JavaScript; se vuelven a bajar",
        &["${CACHE}/typescript"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-cpptools",
        "apps",
        "IntelliSense de C/C++",
        "Cabeceras precompiladas de la extensión de C/C++ de VS Code; se rehacen al reabrir los ficheros",
        &["${CACHE}/vscode-cpptools/ipch"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-poetry",
        "apps",
        "Poetry",
        "Metadatos y distribuciones descargadas por Poetry (no toca los entornos virtuales)",
        &["${CACHE}/pypoetry/cache", "${CACHE}/pypoetry/artifacts"],
        TipoRegla::Contenido,
    ),

    /* ── Herramientas de IA ───────────────────────────────────────────────── */
    regla(
        "macos-cursor",
        "ia",
        "Cursor",
        "Caché de Cursor; conserva proyectos, historial de sesiones y ajustes",
        &[
            "${CONFIG}/Cursor/Cache/Cache_Data",
            "${CONFIG}/Cursor/Code Cache",
            "${CONFIG}/Cursor/GPUCache",
            "${CONFIG}/Cursor/logs",
            "${CONFIG}/Cursor/CachedData",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "macos-windsurf",
        "ia",
        "Windsurf",
        "Caché de Windsurf; conserva proyectos, historial de sesiones y ajustes",
        &[
            "${CONFIG}/Windsurf/Cache/Cache_Data",
            "${CONFIG}/Windsurf/Code Cache",
            "${CONFIG}/Windsurf/GPUCache",
            "${CONFIG}/Windsurf/logs",
            "${CONFIG}/Windsurf/CachedData",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "macos-claude",
        "ia",
        "Claude",
        "Cachés de Claude Desktop y Claude Code; NO toca conversaciones, proyectos, configuración, plugins ni copias de seguridad",
        &[
            "${CONFIG}/Claude/Cache/Cache_Data",
            "${CONFIG}/Claude/Code Cache",
            "${CONFIG}/Claude/GPUCache",
            "${HOME}/.claude/cache",
            "${HOME}/.claude/plugins/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "macos-claude-logs",
        "ia",
        "Claude (registros)",
        "Registros de diagnóstico de Claude de más de una semana; nunca toca conversaciones ni historial de ficheros",
        &["${LIBRARY}/Logs/Claude", "${HOME}/.claude/debug", "${HOME}/.claude/logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "macos-codex",
        "ia",
        "Codex",
        "Cachés y ficheros temporales de Codex; conserva sesiones, memorias, credenciales y plugins",
        &["${HOME}/.codex/cache", "${HOME}/.codex/tmp"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),

    /* ── Gráfica ──────────────────────────────────────────────────────────── */
    regla(
        "macos-metal",
        "gpu",
        "Metal (shaders)",
        "Caché de shaders compilados de Metal; el driver la rehace sola, así que la primera vez cada aplicación irá más lenta",
        &["${CACHE}/com.apple.metal"],
        TipoRegla::Contenido,
    )
    .con_reinicio_cache(),
    regla(
        "macos-unity-shaders",
        "gpu",
        "Unity (shaders)",
        "Caché de shaders compilados de Unity; se rehace al abrir los proyectos, así que la primera vez que abras uno irá más lento",
        &["${CACHE}/com.unity3d.UnityEditor"],
        TipoRegla::Contenido,
    )
    .con_reinicio_cache(),

    /* ── Juegos ───────────────────────────────────────────────────────────── */
    regla(
        "macos-steam",
        "juegos",
        "Steam",
        "Registros del cliente de Steam y su caché de descargas web",
        &["${CONFIG}/Steam/logs", "${CONFIG}/Steam/appcache/httpcache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-steam-shaders",
        "juegos",
        "Steam (shaders)",
        "Caché de shaders por juego de la biblioteca por defecto; se recompila al abrir cada juego, así que la primera partida de cada uno irá más lenta",
        &["${CONFIG}/Steam/steamapps/shadercache"],
        TipoRegla::Contenido,
    )
    .con_reinicio_cache(),
    regla(
        "macos-epic",
        "juegos",
        "Epic Games Launcher",
        "Caché web y registros del lanzador de Epic",
        &["${CONFIG}/Epic/EpicGamesLauncher/Saved/webcache", "${LIBRARY}/Logs/EpicGamesLauncher"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-epic-webcache",
        "juegos",
        "Epic (caché web antigua)",
        "Caché web del lanzador de Epic de más de una semana; se rehace sola (cierra el lanzador antes de limpiar)",
        &["${CACHE}/com.epicgames.EpicGamesLauncher/webcache"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "macos-itch",
        "juegos",
        "itch.io",
        "Caché y registros de itch.io",
        &["${CONFIG}/itch/Cache/Cache_Data", "${CONFIG}/itch/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-heroic",
        "juegos",
        "Heroic",
        "Caché web y de GPU de Heroic",
        &["${CONFIG}/heroic/Cache/Cache_Data", "${CONFIG}/heroic/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-minecraft",
        "juegos",
        "Minecraft",
        "Registros, informes de fallo y caché del lanzador de Minecraft",
        &["${CONFIG}/minecraft/logs", "${CONFIG}/minecraft/crash-reports", "${CONFIG}/minecraft/webcache2"],
        TipoRegla::Contenido,
    ),
    regla(
        "macos-roblox",
        "juegos",
        "Roblox",
        "Caché del reproductor de Roblox; sus registros ya los limpia la regla general de registros de usuario",
        &["${CACHE}/com.roblox.RobloxPlayer"],
        TipoRegla::Contenido,
    ),

    /* ── Privacidad (huellas) ─────────────────────────────────────────────── */
    // Estas NO son basura que se regenere sola: son huellas de TU actividad.
    // Borrarlas no lo vuelve a crear nadie, así que van marcadas con
    // `.marcar_traza()` y solo se limpian si se pide la categoría `privacidad`.
    regla(
        "macos-hist-zsh",
        "privacidad",
        "Historial de zsh",
        "Las órdenes que has escrito en zsh. NO se recupera: si lo borras, se ha ido",
        &["${HOME}/.zsh_history"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-hist-bash",
        "privacidad",
        "Historial de bash",
        "Las órdenes que has escrito en bash. NO se recupera: si lo borras, se ha ido",
        &["${HOME}/.bash_history"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-hist-python",
        "privacidad",
        "Historial de Python",
        "Las últimas órdenes que has escrito dentro del intérprete de Python. NO se recupera",
        &["${HOME}/.python_history", "${HOME}/.python_history-*"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-hist-editor",
        "privacidad",
        "Historial de vim y less",
        "Historial y estado de vim y de less (ficheros abiertos, búsquedas). NO se recupera",
        &["${HOME}/.viminfo", "${HOME}/.lesshst"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-zsh-sessions",
        "privacidad",
        "Sesiones guardadas de zsh",
        "Las sesiones que guarda zsh de tus terminales anteriores, con su salida. NO se recupera",
        &["${HOME}/.zsh_sessions"],
        TipoRegla::Contenido,
    )
    .marcar_traza(),
    regla(
        "macos-recientes",
        "privacidad",
        "Elementos recientes",
        "Las listas de recientes de macOS (documentos, aplicaciones, servidores y hosts). NO se recupera; no toca las listas de favoritos",
        &["${LIBRARY}/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.Recent*.sfl*"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-recientes-apps",
        "privacidad",
        "Documentos recientes por aplicación",
        "Las listas de documentos recientes que guarda cada aplicación. NO se recupera",
        &["${LIBRARY}/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/*.sfl*"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-recentitems",
        "privacidad",
        "Preferencias de recientes",
        "Las preferencias de elementos recientes del sistema. NO se recupera",
        &["${LIBRARY}/Preferences/com.apple.recentitems.plist"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "macos-descargas-cuarentena",
        "privacidad",
        "Historial de descargas (Gatekeeper)",
        "El historial de descargas que guarda Gatekeeper: qué bajaste y desde dónde. NO se recupera; macOS vuelve a crear la base de datos vacía",
        &["${LIBRARY}/Preferences/com.apple.LaunchServices.QuarantineEventsV2"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
];
