//! Catálogo de limpieza de **Windows**.
//!
//! Las rutas están tomadas de `rules/win32/*.json` de [Kudu](https://github.com/adventdevinc/kudu)
//! (MIT); los textos están en español porque toda la interfaz lo está. Aquí NO se
//! inventa ninguna ruta.
//!
//! Kudu escribe sus rutas con sus propias variables; aquí se traducen a las
//! nuestras cuando significan lo mismo (su `${LOCALAPPDATA}` y su `${APPDATA}` son
//! los nuestros, y su `childSubdir` se traduce en un comodín). Cuando Kudu marca
//! `minAgeDays` se usa `.con_dias_como(n)`; cuando marca `needsAdmin`,
//! `.con_root_como("...")` con el comando real de Windows (la app NO lo lanza:
//! enseña el comando), y cuando marca `cleanupAction`, `.con_comando_como("...")`.
//!
//! Variables disponibles (las resuelve `expandir`, en `limpieza.rs`):
//! `${HOME}`, `${LOCALAPPDATA}` (`AppData\Local`), `${APPDATA}` (`AppData\Roaming`),
//! `${TEMP}`, `${WINDIR}`, `${PROGRAMFILES}`, `${PROGRAMFILES_X86}`, `${PROGRAMDATA}`,
//! `${SYSTEMDRIVE}`. En un sistema que no sea Windows esas rutas no existen y la
//! regla que las use simplemente no encuentra nada.
//!
//! La sección `privacidad` son huellas de TU actividad (historiales de shell,
//! recientes, listas de salto, portapapeles): NO se regeneran solas, van marcadas
//! con `.marcar_traza()` y solo se limpian si se pide esa categoría.
use super::{regla, CoincidenciaFicheros, CoincidenciaRecursiva, Regla, TipoRegla};

/// Nombres de carpeta de caché que Kudu borra bajo el ancla de las «particiones»
/// de Chromium (Claude, ChatGPT, Codex, Cursor, T3 Code y Spotify). Son las
/// que declara su `recursiveMatch`, ni una más: no se inventa ningún objetivo.
const CACHES_DE_PARTICION: &[&str] = &[
    "Cache",
    "Code Cache",
    "GPUCache",
    "DawnCache",
    "DawnGraphiteCache",
    "DawnWebGPUCache",
];

/// Ramas que NUNCA se inspeccionan bajo una partición: ahí viven sesiones,
/// almacenamiento local, IndexedDB, datos de service worker y contenido sin
/// conexión. Son las `excludedAncestors` de Kudu, y están por un motivo: borrar
/// dentro sería llevarse la sesión de alguien, así que el motor no baja a mirar
/// esas carpetas.
const RAMAS_DE_DATOS_PARTICION: &[&str] = &[
    "File System",
    "IndexedDB",
    "Local Storage",
    "Network",
    "Service Worker",
    "Session Storage",
    "Sessions",
    "Sync Data",
    "WebStorage",
    "blob_storage",
    "databases",
];

/// Objetivos y exclusiones del `recursiveMatch` de WebView2: Kudu no excluye
/// `Sessions` ni `Sync Data` aquí (no son rutas de WebView2) y tampoco borra
/// `DawnCache`, así que no se añaden.
const CACHES_DE_WEBVIEW2: &[&str] = &[
    "Cache",
    "Code Cache",
    "GPUCache",
    "DawnGraphiteCache",
    "DawnWebGPUCache",
];
const RAMAS_DE_DATOS_WEBVIEW2: &[&str] = &[
    "File System",
    "IndexedDB",
    "Local Storage",
    "Network",
    "Service Worker",
    "Session Storage",
    "WebStorage",
    "blob_storage",
    "databases",
];

pub const REGLAS: &[Regla] = &[
    /* ── Sistema ──────────────────────────────────────────────────────────── */
    regla(
        "win-temp-usuario",
        "sistema",
        "Temporales del usuario",
        "Ficheros temporales de tus programas; los de menos de un día se conservan porque pueden estar en uso",
        &["${LOCALAPPDATA}/Temp"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-temp-sistema",
        "sistema",
        "Temporales de Windows",
        "Temporales que crean los servicios y los procesos del sistema",
        &["${WINDIR}/Temp"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-temp-cuenta-sistema",
        "sistema",
        "Temporales de la cuenta SYSTEM",
        "Temporales de los procesos que corren como SYSTEM en Windows 11 (necesita permisos de administrador)",
        &["${WINDIR}/SystemTemp"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\SystemTemp\\*\""),
    regla(
        "win-prefetch",
        "sistema",
        "Prefetch",
        "Ficheros de prefetch que Windows usa para arrancar los programas más rápido; se regeneran al abrirlos (necesita permisos de administrador)",
        &["${WINDIR}/Prefetch"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\Prefetch\\*\""),
    regla(
        "win-logs-sistema",
        "sistema",
        "Registros de Windows",
        "Registros del sistema y de sus componentes (CBS y DISM incluidos); necesita permisos de administrador",
        &["${WINDIR}/Logs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\Logs\\*\""),
    regla(
        "win-miniaturas",
        "sistema",
        "Miniaturas del explorador",
        "Base de datos de miniaturas e iconos del explorador; se rehace al abrir carpetas",
        &["${LOCALAPPDATA}/Microsoft/Windows/Explorer"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-fuentes",
        "sistema",
        "Caché de fuentes",
        "Caché de renderizado de fuentes del servicio Font Cache (necesita permisos de administrador); se rehace sola",
        &["${WINDIR}/ServiceProfiles/LocalService/AppData/Local/FontCache"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\ServiceProfiles\\LocalService\\AppData\\Local\\FontCache\\*\""),
    regla(
        "win-d3ds-cache",
        "sistema",
        "Caché de shaders de DirectX",
        "Shaders compilados de DirectX que aceleran el arranque de juegos y aplicaciones; se recompilan al usarlos",
        &["${LOCALAPPDATA}/D3DSCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-inetcache",
        "sistema",
        "Caché de Internet",
        "Contenido web en caché de los componentes del sistema y del antiguo Internet Explorer",
        &["${LOCALAPPDATA}/Microsoft/Windows/INetCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-update-cache",
        "sistema",
        "Caché de Windows Update",
        "Paquetes de actualización descargados; puede incluir actualizaciones pendientes que habrá que volver a bajar (necesita permisos de administrador)",
        &["${WINDIR}/SoftwareDistribution/Download"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\SoftwareDistribution\\Download\\*\""),
    regla(
        "win-delivery-optimization",
        "sistema",
        "Caché de optimización de entrega",
        "Caché que Windows usa para repartir actualizaciones; se limpia con su propia herramienta y necesita permisos de administrador",
        &["${WINDIR}/SoftwareDistribution/DeliveryOptimization"],
        TipoRegla::Contenido,
    )
    .con_root_como("Delete-DeliveryOptimizationCache -Force"),
    regla(
        "win-winsxs",
        "sistema",
        "Componentes de Windows",
        "Versiones antiguas de componentes que Windows ya no usa; se quitan con DISM y necesita permisos de administrador",
        &["${WINDIR}/WinSxS"],
        TipoRegla::Contenido,
    )
    .con_root_como("DISM /Online /Cleanup-Image /StartComponentCleanup"),
    regla(
        "win-wer-usuario",
        "sistema",
        "Informes de errores",
        "Informes de problemas y fallos que Windows Error Reporting guarda para tu usuario",
        &["${LOCALAPPDATA}/Microsoft/Windows/WER"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-crash-dumps",
        "sistema",
        "Volcados de fallo",
        "Volcados que Windows guarda cuando un programa se cierra mal",
        &["${LOCALAPPDATA}/CrashDumps"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-minidump",
        "sistema",
        "Minivolcados del núcleo",
        "Volcados del núcleo que Windows crea al fallar con pantalla azul (necesita permisos de administrador)",
        &["${WINDIR}/Minidump"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\Minidump\\*\""),
    regla(
        "win-panther",
        "sistema",
        "Registros de instalación",
        "Registros de la instalación y las actualizaciones de Windows (necesita permisos de administrador)",
        &["${WINDIR}/Panther"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\Panther\\*\""),
    regla(
        "win-patch-cache",
        "sistema",
        "Caché de parches del instalador",
        "Copias base de los parches MSI que Windows guarda para poder desinstalar (necesita permisos de administrador)",
        &["${WINDIR}/Installer/$PatchCache$"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force -Path (Join-Path $env:WINDIR 'Installer\\$PatchCache$\\*')"),
    regla(
        "win-event-logs",
        "sistema",
        "Archivos del registro de eventos",
        "Ficheros .evtx archivados del registro de eventos de Windows (necesita permisos de administrador)",
        &["${WINDIR}/System32/winevt/Logs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\System32\\winevt\\Logs\\*\""),
    regla(
        "win-debug-logs",
        "sistema",
        "Registros de depuración",
        "Registros que generan servicios de Windows como Netlogon o WIA (necesita permisos de administrador)",
        &["${WINDIR}/debug"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\debug\\*\""),
    regla(
        "win-tracing",
        "sistema",
        "Trazas del sistema",
        "Registros de trazas de diagnóstico de componentes de red y del sistema (necesita permisos de administrador)",
        &["${WINDIR}/tracing"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\tracing\\*\""),
    regla(
        "win-update-db-logs",
        "sistema",
        "Registros de la base de Windows Update",
        "Registros de transacciones de la base de datos de Windows Update (necesita permisos de administrador)",
        &["${WINDIR}/SoftwareDistribution/DataStore/Logs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\SoftwareDistribution\\DataStore\\Logs\\*\""),
    regla(
        "win-firewall-logs",
        "sistema",
        "Registros del cortafuegos",
        "Registros de actividad del cortafuegos de Windows, con las conexiones permitidas y bloqueadas (necesita permisos de administrador)",
        &["${WINDIR}/System32/LogFiles/Firewall"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\System32\\LogFiles\\Firewall\\*\""),
    regla(
        "win-winsat",
        "sistema",
        "Resultados de WinSAT",
        "Resultados de las pruebas de rendimiento de Windows System Assessment Tool (necesita permisos de administrador)",
        &["${WINDIR}/Performance/WinSAT/DataStore"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\Performance\\WinSAT\\DataStore\\*\""),
    regla(
        "win-cuentas-sistema-temp",
        "sistema",
        "Temporales de las cuentas de servicio",
        "Temporales que crean las cuentas Network Service, Local Service y Local System (necesita permisos de administrador)",
        &[
            "${WINDIR}/ServiceProfiles/NetworkService/AppData/Local/Temp",
            "${WINDIR}/ServiceProfiles/LocalService/AppData/Local/Temp",
            "${WINDIR}/ServiceProfiles/LocalSystem/AppData/Local/Temp",
        ],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\ServiceProfiles\\NetworkService\\AppData\\Local\\Temp\\*\", \"$env:WINDIR\\ServiceProfiles\\LocalService\\AppData\\Local\\Temp\\*\", \"$env:WINDIR\\ServiceProfiles\\LocalSystem\\AppData\\Local\\Temp\\*\""),
    regla(
        "win-cryptnet-cache",
        "sistema",
        "Caché de certificados",
        "Listas de revocación y respuestas OCSP en caché de las cuentas de servicio (necesita permisos de administrador)",
        &[
            "${WINDIR}/ServiceProfiles/LocalService/AppData/LocalLow/Microsoft/CryptnetUrlCache",
            "${WINDIR}/ServiceProfiles/NetworkService/AppData/LocalLow/Microsoft/CryptnetUrlCache",
            "${WINDIR}/System32/config/systemprofile/AppData/LocalLow/Microsoft/CryptnetUrlCache",
        ],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\ServiceProfiles\\LocalService\\AppData\\LocalLow\\Microsoft\\CryptnetUrlCache\\*\", \"$env:WINDIR\\ServiceProfiles\\NetworkService\\AppData\\LocalLow\\Microsoft\\CryptnetUrlCache\\*\", \"$env:WINDIR\\System32\\config\\systemprofile\\AppData\\LocalLow\\Microsoft\\CryptnetUrlCache\\*\""),
    regla(
        "win-wer-sistema",
        "sistema",
        "Informes de errores del sistema",
        "Informes de problemas y fallos de Windows Error Reporting para todo el equipo (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/Windows/WER"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Windows\\WER\\*\""),
    regla(
        "win-defender-sistema",
        "sistema",
        "Datos de Windows Defender",
        "Historial de análisis, soporte y firmas de Windows Defender (necesita permisos de administrador); no toca la protección en sí",
        &[
            "${PROGRAMDATA}/Microsoft/Windows Defender/Scans/History",
            "${PROGRAMDATA}/Microsoft/Windows Defender/Support",
            "${PROGRAMDATA}/Microsoft/Windows Defender/Scans/MetaStore",
            "${PROGRAMDATA}/Microsoft/Windows Defender/Network Inspection System/Support",
            "${PROGRAMDATA}/Microsoft/Windows Defender/Scans/RtSigs",
        ],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Windows Defender\\Scans\\History\\*\", \"$env:PROGRAMDATA\\Microsoft\\Windows Defender\\Support\\*\", \"$env:PROGRAMDATA\\Microsoft\\Windows Defender\\Scans\\MetaStore\\*\", \"$env:PROGRAMDATA\\Microsoft\\Windows Defender\\Network Inspection System\\Support\\*\", \"$env:PROGRAMDATA\\Microsoft\\Windows Defender\\Scans\\RtSigs\\*\""),
    regla(
        "win-windows-old",
        "sistema",
        "Instalación anterior de Windows",
        "Ficheros de la instalación anterior de Windows, guardados para poder volver atrás; pueden ocupar muchísimo (necesita permisos de administrador)",
        &["${SYSTEMDRIVE}/Windows.old"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:SystemDrive\\Windows.old\""),
    regla(
        "win-memory-dump",
        "sistema",
        "Volcado de memoria completo",
        "Volcado de memoria que Windows crea al fallar con pantalla azul; suele ocupar varios GB (necesita permisos de administrador)",
        &["${WINDIR}/MEMORY.DMP"],
        TipoRegla::Fichero,
    )
    .con_root_como("Remove-Item -Force \"$env:WINDIR\\MEMORY.DMP\""),
    regla(
        "win-clr-usage-logs",
        "sistema",
        "Registros de uso de .NET",
        "Registros de telemetría de uso que genera el runtime de .NET Framework, en 64 y 32 bits",
        &["${LOCALAPPDATA}/Microsoft/CLR_v4.0/UsageLogs", "${LOCALAPPDATA}/Microsoft/CLR_v4.0_32/UsageLogs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-rdp-cache",
        "sistema",
        "Caché de Escritorio remoto",
        "Mosaicos de mapa de bits en caché de las sesiones de Escritorio remoto",
        &["${LOCALAPPDATA}/Microsoft/Terminal Server Client/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-caches-shell",
        "sistema",
        "Cachés del shell de Windows",
        "Cachés de uso general de los componentes del shell de Windows; se rehacen solas",
        &["${LOCALAPPDATA}/Microsoft/Windows/Caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-rac",
        "sistema",
        "Datos del Monitor de confiabilidad",
        "Datos que el componente de análisis de confiabilidad recoge para los informes del Monitor de confiabilidad (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/RAC/PublishedData"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\RAC\\PublishedData\\*\""),
    regla(
        "win-search-gatherlogs",
        "sistema",
        "Registros de Windows Search",
        "Registros del servicio de indexación de Windows Search (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/Search/Data/Applications/Windows/GatherLogs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Search\\Data\\Applications\\Windows\\GatherLogs\\*\""),
    regla(
        "win-diagnostico-etl",
        "sistema",
        "Registros ETL de diagnóstico",
        "Registros de seguimiento de eventos que recoge el diagnóstico de Windows (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/Diagnosis/ETLLogs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Diagnosis\\ETLLogs\\*\""),
    regla(
        "win-power-diagnostics",
        "sistema",
        "Informes de eficiencia energética",
        "Informes de diagnóstico de energía que genera powercfg (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/Windows/Power Efficiency Diagnostics"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Windows\\Power Efficiency Diagnostics\\*\""),
    regla(
        "win-live-kernel-reports",
        "sistema",
        "Volcados del núcleo en vivo",
        "Volcados que el núcleo crea en vivo ante operaciones anómalas sin llegar a colgarse (necesita permisos de administrador)",
        &["${WINDIR}/LiveKernelReports"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\LiveKernelReports\\*\""),
    regla(
        "win-appcompat",
        "sistema",
        "Caché de compatibilidad de aplicaciones",
        "Datos de análisis de compatibilidad e inventario de programas de Windows (necesita permisos de administrador)",
        &["${WINDIR}/AppCompat/Programs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\AppCompat\\Programs\\*\""),
    regla(
        "win-ruxim",
        "sistema",
        "Registros de Windows Update UX",
        "Registros del gestor de interacción de las notificaciones de Windows Update (necesita permisos de administrador)",
        &["${PROGRAMDATA}/Microsoft/Windows/RUXIM"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\Microsoft\\Windows\\RUXIM\\*\""),
    regla(
        "win-qwave",
        "sistema",
        "Caché de qWAVE",
        "Datos de calidad multimedia en caché del servicio Quality Windows Audio/Video Experience (necesita permisos de administrador)",
        &["${WINDIR}/ServiceProfiles/LocalService/AppData/Local/Microsoft/Windows/qWave"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\ServiceProfiles\\LocalService\\AppData\\Local\\Microsoft\\Windows\\qWave\\*\""),
    regla(
        "win-peer-networking",
        "sistema",
        "Trazas de red entre pares",
        "Datos y trazas de conexión del grupo de red entre pares (necesita permisos de administrador)",
        &["${WINDIR}/ServiceProfiles/LocalService/AppData/Local/PeerNetworking"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\ServiceProfiles\\LocalService\\AppData\\Local\\PeerNetworking\\*\""),
    regla(
        "win-wmi-logs",
        "sistema",
        "Registros de trazas de WMI",
        "Registros de seguimiento de eventos del Instrumental de administración de Windows (necesita permisos de administrador)",
        &["${WINDIR}/System32/LogFiles/WMI"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\System32\\LogFiles\\WMI\\*\""),
    regla(
        "win-httperr-logs",
        "sistema",
        "Registros de errores HTTP",
        "Registros de errores del servicio HTTP de Windows (HTTP.sys) (necesita permisos de administrador)",
        &["${WINDIR}/System32/LogFiles/HTTPERR"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\System32\\LogFiles\\HTTPERR\\*\""),
    regla(
        "win-elevated-diagnostics",
        "sistema",
        "Diagnósticos con privilegios",
        "Resultados de los solucionadores de problemas de diagnóstico elevados",
        &["${LOCALAPPDATA}/ElevatedDiagnostics"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-setup-cln",
        "sistema",
        "Registros de limpieza de instalación",
        "Registros de las operaciones de limpieza de la instalación de Windows (necesita permisos de administrador)",
        &["${WINDIR}/System32/LogFiles/setupcln"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:WINDIR\\System32\\LogFiles\\setupcln\\*\""),
    regla(
        "win-uso-shared",
        "sistema",
        "Registros del orquestador de actualizaciones",
        "Registros de diagnóstico del orquestador de Windows Update; los activos y recientes se conservan (necesita permisos de administrador)",
        &["${PROGRAMDATA}/USOShared/Logs"],
        TipoRegla::Contenido,
    )
    .con_root_como("Remove-Item -Recurse -Force \"$env:PROGRAMDATA\\USOShared\\Logs\\*\""),
    regla(
        "win-energy-report",
        "sistema",
        "Informe de energía",
        "Informe de diagnóstico de energía que genera `powercfg /energy` (necesita permisos de administrador)",
        &["${WINDIR}/System32/energy-report.html"],
        TipoRegla::Fichero,
    )
    .con_root_como("Remove-Item -Force \"$env:WINDIR\\System32\\energy-report.html\""),

    /* ── Navegadores ──────────────────────────────────────────────────────── */
    regla(
        "win-chrome",
        "navegadores",
        "Google Chrome",
        "Caché de Chrome; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Google/Chrome/User Data/Default/Cache",
            "${LOCALAPPDATA}/Google/Chrome/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Google/Chrome/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-edge",
        "navegadores",
        "Microsoft Edge",
        "Caché de Edge; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Microsoft/Edge/User Data/Default/Cache",
            "${LOCALAPPDATA}/Microsoft/Edge/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Microsoft/Edge/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-firefox",
        "navegadores",
        "Firefox",
        "Caché web de todos los perfiles de Firefox; conserva historial, marcadores y contraseñas",
        &["${LOCALAPPDATA}/Mozilla/Firefox/Profiles/*/cache2"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-brave",
        "navegadores",
        "Brave",
        "Caché de Brave; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/BraveSoftware/Brave-Browser/User Data/Default/Cache",
            "${LOCALAPPDATA}/BraveSoftware/Brave-Browser/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/BraveSoftware/Brave-Browser/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vivaldi",
        "navegadores",
        "Vivaldi",
        "Caché de Vivaldi; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Vivaldi/User Data/Default/Cache",
            "${LOCALAPPDATA}/Vivaldi/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Vivaldi/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-opera",
        "navegadores",
        "Opera",
        "Caché de Opera y Opera GX; conserva perfiles, historial y contraseñas",
        &[
            "${APPDATA}/Opera Software/Opera Stable/Cache",
            "${APPDATA}/Opera Software/Opera Stable/Code Cache",
            "${APPDATA}/Opera Software/Opera Stable/GPUCache",
            "${APPDATA}/Opera Software/Opera GX Stable/Cache",
            "${APPDATA}/Opera Software/Opera GX Stable/Code Cache",
            "${APPDATA}/Opera Software/Opera GX Stable/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-arc",
        "navegadores",
        "Arc",
        "Caché de Arc; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Arc/User Data/Default/Cache",
            "${LOCALAPPDATA}/Arc/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Arc/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-chromium",
        "navegadores",
        "Chromium",
        "Caché de Chromium; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Chromium/User Data/Default/Cache",
            "${LOCALAPPDATA}/Chromium/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Chromium/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-thorium",
        "navegadores",
        "Thorium",
        "Caché de Thorium; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Thorium/User Data/Default/Cache",
            "${LOCALAPPDATA}/Thorium/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Thorium/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-supermium",
        "navegadores",
        "Supermium",
        "Caché de Supermium; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Supermium/User Data/Default/Cache",
            "${LOCALAPPDATA}/Supermium/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Supermium/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    // Navegadores Chromium que Kudu limpia y a nosotros nos faltaban por
    // completo. Se sigue la misma forma que las reglas de arriba (perfil
    // `Default`, que es el que usa la mayoría), no una segunda convención.
    regla(
        "win-helium",
        "navegadores",
        "Helium",
        "Caché de Helium; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/imput/Helium/User Data/Default/Cache",
            "${LOCALAPPDATA}/imput/Helium/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/imput/Helium/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-cromite",
        "navegadores",
        "Cromite",
        "Caché de Cromite; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/Cromite/User Data/Default/Cache",
            "${LOCALAPPDATA}/Cromite/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/Cromite/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-catsxp",
        "navegadores",
        "CatsXP",
        "Caché de CatsXP; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/ArcSoft/CatsXP/User Data/Default/Cache",
            "${LOCALAPPDATA}/ArcSoft/CatsXP/User Data/Default/Code Cache",
            "${LOCALAPPDATA}/ArcSoft/CatsXP/User Data/Default/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-navegadores-firefox",
        "navegadores",
        "Navegadores basados en Firefox",
        "Caché web de LibreWolf, Waterfox, Floorp y Zen; conserva perfiles, historial y contraseñas",
        &[
            "${LOCALAPPDATA}/LibreWolf/Profiles/*/cache2",
            "${LOCALAPPDATA}/Waterfox/Profiles/*/cache2",
            "${LOCALAPPDATA}/Floorp/Profiles/*/cache2",
            "${LOCALAPPDATA}/Zen/Profiles/*/cache2",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-thunderbird",
        "navegadores",
        "Thunderbird",
        "Caché web de cada perfil de Thunderbird; conserva el correo y las cuentas",
        &["${LOCALAPPDATA}/Thunderbird/Profiles/*/cache2"],
        TipoRegla::Contenido,
    ),

    /* ── Aplicaciones y desarrollo ────────────────────────────────────────── */
    regla(
        "win-npm",
        "apps",
        "npm",
        "Paquetes y metadatos que descarga npm, en su ubicación actual y en la antigua; se vuelven a bajar",
        &["${LOCALAPPDATA}/npm-cache", "${APPDATA}/npm-cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-yarn",
        "apps",
        "Yarn",
        "Paquetes descargados por Yarn; `yarn cache clean` haría lo mismo",
        &["${LOCALAPPDATA}/Yarn/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-pnpm",
        "apps",
        "pnpm (almacén)",
        "pnpm limpia su almacén mejor con su comando: borra lo que ya no referencia ningún proyecto y conserva el resto",
        &["${LOCALAPPDATA}/pnpm/store", "${LOCALAPPDATA}/pnpm-cache", "${LOCALAPPDATA}/pnpm-store", "${HOME}/.pnpm-store"],
        TipoRegla::Comando,
    )
    .con_comando_como("pnpm store prune"),
    regla(
        "win-pip",
        "apps",
        "pip y Pipenv",
        "Ruedas y distribuciones descargadas por pip y Pipenv; se vuelven a bajar",
        &["${LOCALAPPDATA}/pip/Cache", "${LOCALAPPDATA}/pipenv/pipenv/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-uv",
        "apps",
        "uv (caché)",
        "uv limpia su caché mejor con su comando: conserva lo que sigue en uso",
        &["${HOME}"],
        TipoRegla::Comando,
    )
    .con_comando_como("uv cache prune"),
    regla(
        "win-bun",
        "apps",
        "Bun",
        "Paquetes descargados por Bun",
        &["${HOME}/.bun/install/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-cargo",
        "apps",
        "Cargo",
        "Ficheros .crate descargados, fuentes extraídas y checkouts de git; se rehacen al compilar",
        &["${HOME}/.cargo/registry/cache", "${HOME}/.cargo/registry/src", "${HOME}/.cargo/git/checkouts"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-go",
        "apps",
        "Go",
        "Módulos descargados y caché del compilador de Go; se rehacen en la siguiente compilación",
        &["${HOME}/go/pkg/mod/cache", "${LOCALAPPDATA}/go-build"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-gradle",
        "apps",
        "Gradle",
        "Cachés de compilación y registros del demonio de Gradle",
        &["${HOME}/.gradle/caches", "${HOME}/.gradle/daemon"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-docker",
        "apps",
        "Docker Desktop",
        "Cachés de Docker Desktop y sus registros del host y de la máquina virtual; los ficheros de menos de un día se conservan",
        &[
            "${APPDATA}/Docker Desktop/cache",
            "${APPDATA}/Docker Desktop/Code Cache",
            "${APPDATA}/Docker Desktop/GPUCache",
            "${LOCALAPPDATA}/Docker/log/host",
            "${LOCALAPPDATA}/Docker/log/vm",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-docker-build",
        "apps",
        "Docker (caché de compilación)",
        "Docker limpia su caché de compilación mejor con su comando (no toca contenedores, volúmenes ni imágenes)",
        &["${HOME}"],
        TipoRegla::Comando,
    )
    .con_comando_como("docker builder prune"),
    regla(
        "win-nuget",
        "apps",
        "NuGet",
        "Caché de respuestas HTTP y de plugins de NuGet; se vuelve a pedir al restaurar paquetes",
        &["${LOCALAPPDATA}/NuGet/v3-cache", "${LOCALAPPDATA}/NuGet/plugins-cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vscode",
        "apps",
        "Visual Studio Code",
        "Caché web, de código compilado y de GPU de VS Code, paquetes de extensiones descargados y registros; conserva los ajustes y las extensiones instaladas",
        &[
            "${APPDATA}/Code/Cache/Cache_Data",
            "${APPDATA}/Code/Code Cache",
            "${APPDATA}/Code/GPUCache",
            "${APPDATA}/Code/CachedData",
            "${APPDATA}/Code/CachedExtensions",
            "${APPDATA}/Code/CachedExtensionVSIXs",
            "${APPDATA}/Code/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-jetbrains",
        "apps",
        "JetBrains",
        "Cachés de los IDE de JetBrains (IntelliJ, PyCharm, WebStorm…); se rehacen al reiniciar",
        &["${LOCALAPPDATA}/JetBrains/*/caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-visual-studio",
        "apps",
        "Visual Studio",
        "Caché del modelo de componentes MEF de Visual Studio; se rehace al reiniciar",
        &["${LOCALAPPDATA}/Microsoft/VisualStudio/*/ComponentModelCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-android-studio",
        "apps",
        "Android Studio",
        "Cachés por versión de Android Studio y de otros productos de Google; se rehacen al usarlos",
        &["${LOCALAPPDATA}/Google/*/caches"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-discord",
        "apps",
        "Discord",
        "Caché web, de código compilado y de GPU de Discord, además de sus registros; conserva sesiones, cuenta y ajustes",
        &[
            "${APPDATA}/discord/Cache/Cache_Data",
            "${APPDATA}/discord/Code Cache",
            "${APPDATA}/discord/GPUCache",
            "${APPDATA}/discord/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-teams",
        "apps",
        "Microsoft Teams",
        "Caché web de Microsoft Teams; conserva cuenta, chats y ajustes",
        &["${APPDATA}/Microsoft/Teams/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-slack",
        "apps",
        "Slack",
        "Caché web, de código compilado y de GPU de Slack, además de sus registros; conserva sesiones, cuenta y ajustes",
        &[
            "${APPDATA}/Slack/Cache/Cache_Data",
            "${APPDATA}/Slack/Code Cache",
            "${APPDATA}/Slack/GPUCache",
            "${APPDATA}/Slack/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-zoom",
        "apps",
        "Zoom",
        "Caché web y de GPU de Zoom, además de sus registros; conserva cuenta, reuniones y ajustes",
        &[
            "${APPDATA}/Zoom/data/Cache",
            "${APPDATA}/Zoom/data/GPUCache",
            "${APPDATA}/Zoom/data/logs",
            "${APPDATA}/Zoom/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-telegram",
        "apps",
        "Telegram",
        "Caché de datos de usuario y de emoji de Telegram; conserva chats, cuenta y ajustes",
        &[
            "${APPDATA}/Telegram Desktop/tdata/user_data",
            "${APPDATA}/Telegram Desktop/tdata/emoji",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-spotify",
        "apps",
        "Spotify",
        "Almacenamiento sin conexión y datos en caché de Spotify; conserva cuenta, listas y ajustes",
        &["${LOCALAPPDATA}/Spotify/Storage", "${LOCALAPPDATA}/Spotify/Data"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-obs",
        "apps",
        "OBS Studio",
        "Registros y datos del generador de perfiles de OBS Studio; conserva escenas, fuentes y ajustes",
        &["${APPDATA}/obs-studio/logs", "${APPDATA}/obs-studio/profiler_data"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-adobe",
        "apps",
        "Adobe Creative Cloud",
        "Caché CEF de Acrobat y caché de medios compartida de Premiere, After Effects y compañía; se rehace al abrir los proyectos",
        &[
            "${LOCALAPPDATA}/Adobe/AcroCef/Cache",
            "${APPDATA}/Adobe/Common/Media Cache Files",
            "${APPDATA}/Adobe/Common/Media Cache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-sccache",
        "apps",
        "sccache",
        "Caché de compilación compartida de Rust y C/C++; la próxima compilación solo tardará más",
        &["${LOCALAPPDATA}/Mozilla/sccache/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-maven",
        "apps",
        "Maven",
        "Repositorio local de Maven con los artefactos descargados; se vuelven a bajar al compilar",
        &["${HOME}/.m2/repository"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-modern-mtr",
        "apps",
        "Modern MTR",
        "Caché web, de código compilado y de GPU de Modern MTR; se rehace al abrir la aplicación",
        &[
            "${APPDATA}/Modern MTR/Cache/Cache_Data",
            "${APPDATA}/Modern MTR/Code Cache",
            "${APPDATA}/Modern MTR/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-composer",
        "apps",
        "Composer",
        "Caché de paquetes PHP descargados por Composer; se vuelven a bajar al instalar",
        &["${LOCALAPPDATA}/Composer/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-signal",
        "apps",
        "Signal Desktop",
        "Caché web y de GPU de Signal Desktop; conserva mensajes, cuenta y ajustes",
        &["${APPDATA}/Signal/Cache/Cache_Data", "${APPDATA}/Signal/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-postman",
        "apps",
        "Postman",
        "Caché web y de GPU de Postman; conserva colecciones, entornos y cuenta",
        &["${APPDATA}/Postman/Cache/Cache_Data", "${APPDATA}/Postman/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-figma",
        "apps",
        "Figma",
        "Caché web y de GPU de Figma; conserva archivos, sesiones y cuenta",
        &["${APPDATA}/Figma/Cache/Cache_Data", "${APPDATA}/Figma/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-github-desktop",
        "apps",
        "GitHub Desktop",
        "Caché web y de GPU de GitHub Desktop; conserva repositorios, credenciales y ajustes",
        &["${APPDATA}/GitHub Desktop/Cache/Cache_Data", "${APPDATA}/GitHub Desktop/GPUCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vlc",
        "apps",
        "VLC",
        "Caché de carátulas y miniaturas de VLC; se vuelve a generar al explorar la biblioteca",
        &["${APPDATA}/vlc/art_cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-gimp",
        "apps",
        "GIMP",
        "Temporales y ficheros de trabajo de GIMP; conserva ajustes, pinceles y proyectos guardados",
        &["${APPDATA}/GIMP/*/tmp"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-blender",
        "apps",
        "Blender",
        "Caché de miniaturas y de scripts por versión de Blender; se rehace al abrir la aplicación",
        &["${APPDATA}/Blender Foundation/Blender/*/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-libreoffice",
        "apps",
        "LibreOffice",
        "Datos en caché de LibreOffice, incluidas las miniaturas de extensiones; se rehace al usar la suite",
        &["${APPDATA}/LibreOffice/*/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-teamviewer",
        "apps",
        "TeamViewer",
        "Registros de sesión de TeamViewer; conserva la configuración y la cuenta",
        &["${APPDATA}/TeamViewer/Logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-google-earth",
        "apps",
        "Google Earth",
        "Caché de teselas de imágenes por satélite de Google Earth; se vuelven a descargar al explorar el mapa",
        &["${LOCALAPPDATA}/Google/GoogleEarth/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-inkscape",
        "apps",
        "Inkscape",
        "Caché de fuentes y de renderizado de Inkscape; se rehace al abrir la aplicación",
        &["${LOCALAPPDATA}/inkscape/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-krita",
        "apps",
        "Krita",
        "Caché de recursos y de renderizado de Krita; se rehace al abrir la aplicación",
        &["${LOCALAPPDATA}/krita/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-filezilla",
        "apps",
        "FileZilla",
        "Caché de listados de directorios de FileZilla; conserva los sitios y las credenciales",
        &["${APPDATA}/FileZilla/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-fontconfig",
        "apps",
        "fontconfig",
        "Índice de fuentes que genera fontconfig; se reconstruye solo",
        &["${LOCALAPPDATA}/fontconfig/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-pidgin",
        "apps",
        "Pidgin",
        "Caché de iconos de contactos de Pidgin; se vuelve a descargar al abrir la aplicación",
        &["${APPDATA}/.purple/icons"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-transmission",
        "apps",
        "Transmission",
        "Caché del cliente BitTorrent Transmission; no toca las descargas",
        &["${LOCALAPPDATA}/Transmission/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-conda",
        "apps",
        "Conda",
        "Caché de paquetes descargados por Conda; se vuelven a bajar al instalar",
        &["${HOME}/anaconda3/pkgs", "${HOME}/miniconda3/pkgs", "${HOME}/.conda/pkgs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-notion",
        "apps",
        "Notion",
        "Caché web, de código compilado, de GPU, de shaders, de diccionario y de registros de Notion; conserva sesiones y datos sin conexión",
        &[
            "${APPDATA}/Notion/Cache/Cache_Data",
            "${APPDATA}/Notion/Code Cache",
            "${APPDATA}/Notion/GPUCache",
            "${APPDATA}/Notion/logs",
            "${APPDATA}/Notion/Partitions/notion/Cache/Cache_Data",
            "${APPDATA}/Notion/Partitions/notion/Code Cache",
            "${APPDATA}/Notion/Partitions/notion/GPUCache",
            "${APPDATA}/Notion/Partitions/notion/DawnCache",
            "${APPDATA}/Notion/Partitions/notion/DawnGraphiteCache",
            "${APPDATA}/Notion/Partitions/notion/DawnWebGPUCache",
            "${APPDATA}/Notion/Partitions/notion/Shared Dictionary/cache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-obsidian",
        "apps",
        "Obsidian",
        "Caché web, de código compilado y de GPU de Obsidian; conserva las notas y la bóveda",
        &[
            "${APPDATA}/obsidian/Cache/Cache_Data",
            "${APPDATA}/obsidian/Code Cache",
            "${APPDATA}/obsidian/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-whatsapp",
        "apps",
        "WhatsApp Desktop",
        "Caché web, de código compilado y de GPU de WhatsApp Desktop; conserva los mensajes y la cuenta",
        &[
            "${APPDATA}/WhatsApp/Cache/Cache_Data",
            "${APPDATA}/WhatsApp/Code Cache",
            "${APPDATA}/WhatsApp/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-bitwarden",
        "apps",
        "Bitwarden",
        "Caché web, de código compilado y de GPU de Bitwarden; conserva la caja fuerte y la cuenta",
        &[
            "${APPDATA}/Bitwarden/Cache/Cache_Data",
            "${APPDATA}/Bitwarden/Code Cache",
            "${APPDATA}/Bitwarden/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-1password",
        "apps",
        "1Password",
        "Caché web, de código compilado y de GPU de 1Password; conserva las contraseñas y la cuenta",
        &[
            "${APPDATA}/1Password/Cache/Cache_Data",
            "${APPDATA}/1Password/Code Cache",
            "${APPDATA}/1Password/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-ruby-gems",
        "apps",
        "RubyGems",
        "Caché de ficheros .gem descargados por RubyGems; se vuelven a bajar al instalar",
        &["${HOME}/.gem/*/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-deno",
        "apps",
        "Deno",
        "Caché de módulos de Deno; se vuelven a descargar cuando hagan falta",
        &["${LOCALAPPDATA}/deno"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-sublime-text",
        "apps",
        "Sublime Text",
        "Caché de índices y de recursos de Sublime Text; se rehace al abrir la aplicación",
        &["${LOCALAPPDATA}/Sublime Text/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-termius",
        "apps",
        "Termius",
        "Caché web, de código compilado y de GPU de Termius; conserva hosts, credenciales y ajustes",
        &[
            "${APPDATA}/Termius/Cache/Cache_Data",
            "${APPDATA}/Termius/Code Cache",
            "${APPDATA}/Termius/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-ledger-live",
        "apps",
        "Ledger Live",
        "Caché web, de código compilado y de GPU de Ledger Live; conserva las cuentas y las carteras",
        &[
            "${APPDATA}/Ledger Live/Cache/Cache_Data",
            "${APPDATA}/Ledger Live/Code Cache",
            "${APPDATA}/Ledger Live/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-node-gyp",
        "apps",
        "node-gyp",
        "Caché de cabeceras de compilación de complementos nativos de Node.js; se vuelve a descargar cuando haga falta",
        &["${LOCALAPPDATA}/node-gyp/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-electron-builder",
        "apps",
        "electron-builder",
        "Caché de descargas de electron-builder; se vuelve a descargar cuando haga falta",
        &["${LOCALAPPDATA}/electron-builder/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-electron",
        "apps",
        "Electron",
        "Caché de archivos y distribuciones del entorno de ejecución de Electron descargados; se vuelven a descargar cuando hagan falta",
        &["${LOCALAPPDATA}/electron/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-ffmpeg-static",
        "apps",
        "ffmpeg-static",
        "Caché de binarios y metadatos de ffmpeg-static; se vuelve a descargar cuando haga falta",
        &["${LOCALAPPDATA}/ffmpeg-static-nodejs/Cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-curseforge",
        "apps",
        "CurseForge",
        "Caché web, de GPU y registros del gestor de mods CurseForge; conserva los mods instalados",
        &[
            "${APPDATA}/CurseForge/Cache/Cache_Data",
            "${APPDATA}/CurseForge/Code Cache",
            "${APPDATA}/CurseForge/GPUCache",
            "${APPDATA}/CurseForge/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-logitech-ghub",
        "apps",
        "Logitech G HUB",
        "Caché web de G HUB y paquetes descargados; se conservan los ficheros usados en la última semana",
        &[
            "${APPDATA}/G HUB/Cache/Cache_Data",
            "${APPDATA}/G HUB/Code Cache",
            "${APPDATA}/G HUB/GPUCache",
            "${PROGRAMDATA}/LGHUB/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-kodi",
        "apps",
        "Kodi",
        "Caché y miniaturas de Kodi; pueden ocupar varios GB y se rehacen cuando haga falta",
        &["${APPDATA}/Kodi/cache", "${APPDATA}/Kodi/userdata/Thumbnails"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-qbittorrent",
        "apps",
        "qBittorrent",
        "Registros de qBittorrent; conserva las descargas y la configuración",
        &["${LOCALAPPDATA}/qBittorrent/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-handbrake",
        "apps",
        "HandBrake",
        "Registros de codificaciones anteriores de HandBrake; conserva los vídeos y los ajustes",
        &["${APPDATA}/HandBrake/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-java-cache",
        "apps",
        "Java (caché de despliegue)",
        "Caché de descargas de Java Web Start y applets, una tecnología obsoleta; es seguro borrarla",
        &["${HOME}/AppData/LocalLow/Sun/Java/Deployment/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-hyper",
        "apps",
        "Hyper",
        "Caché web, de código compilado y de GPU de la terminal Hyper; conserva la configuración",
        &[
            "${APPDATA}/Hyper/Cache/Cache_Data",
            "${APPDATA}/Hyper/Code Cache",
            "${APPDATA}/Hyper/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-linear",
        "apps",
        "Linear",
        "Caché web, de código compilado y de GPU de Linear; conserva la cuenta y los datos sincronizados",
        &[
            "${APPDATA}/Linear/Cache/Cache_Data",
            "${APPDATA}/Linear/Code Cache",
            "${APPDATA}/Linear/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-todoist",
        "apps",
        "Todoist",
        "Caché web, de código compilado y de GPU de Todoist; conserva las tareas y la cuenta",
        &[
            "${APPDATA}/Todoist/Cache/Cache_Data",
            "${APPDATA}/Todoist/Code Cache",
            "${APPDATA}/Todoist/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-loom",
        "apps",
        "Loom",
        "Caché web, de código compilado y de GPU de Loom; conserva los vídeos grabados",
        &[
            "${APPDATA}/Loom/Cache/Cache_Data",
            "${APPDATA}/Loom/Code Cache",
            "${APPDATA}/Loom/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-scoop",
        "apps",
        "Scoop",
        "Caché de instaladores descargados por Scoop; se vuelven a bajar cuando hagan falta",
        &["${HOME}/scoop/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-aws-cli",
        "apps",
        "AWS CLI",
        "Caché de respuestas de la API y credenciales temporales de AWS CLI; se vuelven a obtener solas",
        &["${HOME}/.aws/cli/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-gcloud",
        "apps",
        "Google Cloud CLI",
        "Registros y datos en caché de Google Cloud CLI; conserva la configuración y las credenciales",
        &["${APPDATA}/gcloud/logs", "${APPDATA}/gcloud/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-google-drive",
        "apps",
        "Google Drive",
        "Registros rotados y cachés del Chromium integrado de Google Drive; conserva el estado de sincronización y los ficheros sin conexión",
        &[
            "${LOCALAPPDATA}/Google/DriveFS/Logs",
            "${LOCALAPPDATA}/Google/DriveFS/cef_cache/Cache/Cache_Data",
            "${LOCALAPPDATA}/Google/DriveFS/cef_cache/Code Cache",
            "${LOCALAPPDATA}/Google/DriveFS/cef_cache/component_crx_cache",
            "${LOCALAPPDATA}/Google/DriveFS/cef_cache/Shared Dictionary/cache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-kudu",
        "apps",
        "Kudu",
        "Caché web, de código compilado, de GPU y registros del propio Kudu; lo reciente y en uso queda protegido",
        &[
            "${APPDATA}/kudu/Cache/Cache_Data",
            "${APPDATA}/kudu/Code Cache",
            "${APPDATA}/kudu/GPUCache",
            "${APPDATA}/kudu/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-spotify-store-shared",
        "apps",
        "Spotify (Microsoft Store)",
        "Cachés de perfil, shaders, componentes, widgets, lanzador e informes de fallo de Spotify de la Microsoft Store; conserva los datos y el almacenamiento sin conexión",
        &[
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/Code Cache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/GPUCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/DawnCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Default/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/component_crx_cache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/extensions_crx_cache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/GraphiteDawnCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/GrShaderCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/ShaderCache",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/DashboardWidget/logs",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/DashboardWidget/Crashpad/reports",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Launcher/Logs",
            "${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Launcher/Crashpad/reports",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    // El navegador embebido de Spotify de la Store reparte sus vistas en
    // «particiones» anidadas; se borran solo las cachés conocidas de cada una y
    // NO se baja a las ramas de datos (sesión, IndexedDB, almacenamiento local…).
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Browser",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-spotify-store-browser",
            "apps",
            "Spotify (Microsoft Store, particiones)",
            "Cachés dentro de las particiones del navegador de Spotify de la Microsoft Store; conserva la cuenta, las descargas, las sesiones, IndexedDB y los datos sin conexión",
            &["${LOCALAPPDATA}/Packages/SpotifyAB.SpotifyMusic_zpdnekdrzrea0/LocalCache/Spotify/Browser"],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-nvidia-app",
        "apps",
        "NVIDIA App",
        "Cachés del navegador integrado de la NVIDIA App y registros asentados; conserva la cuenta, los ajustes y el estado del controlador",
        &[
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/Cache/Cache_Data",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/Code Cache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/GPUCache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/component_crx_cache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/extensions_crx_cache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/GraphiteDawnCache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/GrShaderCache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NVIDIA app/CefCache/ShaderCache",
            "${PROGRAMDATA}/NVIDIA Corporation/NVIDIA app/Logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-nvidia-driver-downloads",
        "apps",
        "NVIDIA (instaladores)",
        "Instaladores de controladores que la NVIDIA App descargó y ya no usa; solo harían falta para reinstalar esa misma versión",
        &["${PROGRAMDATA}/NVIDIA Corporation/Downloader"],
        TipoRegla::Contenido,
    )
    .con_dias_como(14).con_recencia_profunda(),
    regla(
        "win-amd-installer-files",
        "apps",
        "AMD (instaladores)",
        "Ficheros de instalación que AMD Software extrae en la carpeta AMD y ya no usa tras instalar; los controladores instalados viven en otro sitio",
        &["${SYSTEMDRIVE}/AMD"],
        TipoRegla::Contenido,
    )
    .con_dias_como(14).con_recencia_profunda(),
    regla(
        "win-zed",
        "apps",
        "Zed",
        "Caché de paquetes de Node y registros de Zed; se regeneran cuando hagan falta",
        &["${LOCALAPPDATA}/Zed/node/cache", "${LOCALAPPDATA}/Zed/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vscode-insiders",
        "apps",
        "VS Code Insiders",
        "Caché web, de código compilado y de GPU de VS Code Insiders, paquetes de extensiones descargados y registros; conserva ajustes, extensiones y estado de los espacios de trabajo",
        &[
            "${APPDATA}/Code - Insiders/Cache/Cache_Data",
            "${APPDATA}/Code - Insiders/Code Cache",
            "${APPDATA}/Code - Insiders/GPUCache",
            "${APPDATA}/Code - Insiders/CachedData",
            "${APPDATA}/Code - Insiders/CachedExtensionVSIXs",
            "${APPDATA}/Code - Insiders/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vscodium",
        "apps",
        "VSCodium",
        "Caché web, de código compilado y de GPU de VSCodium, paquetes de extensiones descargados y registros; conserva ajustes, extensiones y estado de los espacios de trabajo",
        &[
            "${APPDATA}/VSCodium/Cache/Cache_Data",
            "${APPDATA}/VSCodium/Code Cache",
            "${APPDATA}/VSCodium/GPUCache",
            "${APPDATA}/VSCodium/CachedData",
            "${APPDATA}/VSCodium/CachedExtensionVSIXs",
            "${APPDATA}/VSCodium/logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-discord-ptb",
        "apps",
        "Discord PTB",
        "Caché web, de código compilado y de GPU de Discord PTB; conserva sesiones, cuenta y ajustes",
        &[
            "${APPDATA}/discordptb/Cache/Cache_Data",
            "${APPDATA}/discordptb/Code Cache",
            "${APPDATA}/discordptb/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-discord-canary",
        "apps",
        "Discord Canary",
        "Caché web, de código compilado y de GPU de Discord Canary; conserva sesiones, cuenta y ajustes",
        &[
            "${APPDATA}/discordcanary/Cache/Cache_Data",
            "${APPDATA}/discordcanary/Code Cache",
            "${APPDATA}/discordcanary/GPUCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-typescript-typings",
        "apps",
        "TypeScript (tipos)",
        "Tipos que el servidor de lenguaje de TypeScript descarga para proyectos JavaScript; se vuelven a bajar cuando hagan falta",
        &["${LOCALAPPDATA}/Microsoft/TypeScript"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-vscode-cpptools",
        "apps",
        "VS Code C/C++",
        "Caché de cabeceras precompiladas de la extensión C/C++ de VS Code; se rehace al reabrir los ficheros",
        &["${LOCALAPPDATA}/Microsoft/vscode-cpptools/ipch"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-poetry",
        "apps",
        "Poetry",
        "Caché de metadatos y distribuciones descargadas por Poetry; la carpeta de entornos virtuales de al lado no se toca",
        &["${LOCALAPPDATA}/pypoetry/Cache/cache", "${LOCALAPPDATA}/pypoetry/Cache/artifacts"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-winget-logs",
        "apps",
        "winget (registros)",
        "Registros de diagnóstico de winget y del Instalador de aplicaciones de más de una semana",
        &["${LOCALAPPDATA}/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe/LocalState/DiagOutputDir"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-onedrive-logs",
        "apps",
        "OneDrive (registros)",
        "Registros del cliente de sincronización y de la instalación de OneDrive de más de una semana; los ficheros y los ajustes no se tocan",
        &["${LOCALAPPDATA}/Microsoft/OneDrive/logs", "${LOCALAPPDATA}/Microsoft/OneDrive/setup/logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-unreal-ddc",
        "apps",
        "Unreal Engine (DDC)",
        "Caché de datos derivados de Unreal Engine (shaders compilados y recursos cocinados); se reconstruye al abrir los proyectos, y puede tardar",
        &["${LOCALAPPDATA}/UnrealEngine/Common/DerivedDataCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-edge-update-logs",
        "apps",
        "Edge Update (registros)",
        "Registros asentados del actualizador de Microsoft Edge; los activos del último día se conservan",
        &["${PROGRAMDATA}/Microsoft/EdgeUpdate/Log"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-firefox-crash-history",
        "apps",
        "Firefox (informes de fallo)",
        "Informes de fallo enviados y eventos de telemetría de Firefox de más de una semana; conserva los ajustes del notificador",
        &[
            "${APPDATA}/Mozilla/Firefox/Crash Reports/submitted",
            "${APPDATA}/Mozilla/Firefox/Crash Reports/events",
            "${APPDATA}/Mozilla/Firefox/Crash Reports/glean",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-firefox-pending-crashes",
        "apps",
        "Firefox (fallos pendientes)",
        "Informes de fallo de Firefox sin enviar y con más de un mes; los recientes y los ajustes se conservan",
        &["${APPDATA}/Mozilla/Firefox/Crash Reports/pending"],
        TipoRegla::Contenido,
    )
    .con_dias_como(30).con_recencia_profunda(),
    regla(
        "win-chocolatey-logs",
        "apps",
        "Chocolatey (registros)",
        "Registros del gestor de paquetes Chocolatey de más de una semana; conserva los paquetes instalados, las copias y la configuración",
        &["${PROGRAMDATA}/chocolatey/logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-bramblewatch",
        "apps",
        "Bramblewatch",
        "Caché web, de código compilado, de GPU, de shaders, de diccionario y registros asentados de Bramblewatch",
        &[
            "${APPDATA}/Bramblewatch/Cache/Cache_Data",
            "${APPDATA}/Bramblewatch/Code Cache",
            "${APPDATA}/Bramblewatch/GPUCache",
            "${APPDATA}/Bramblewatch/DawnGraphiteCache",
            "${APPDATA}/Bramblewatch/DawnWebGPUCache",
            "${APPDATA}/Bramblewatch/Shared Dictionary/cache",
            "${APPDATA}/Bramblewatch/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-hearthglen",
        "apps",
        "Hearthglen",
        "Caché web, de código compilado, de GPU, de shaders y de diccionario de Hearthglen",
        &[
            "${APPDATA}/hearthglen/Cache/Cache_Data",
            "${APPDATA}/hearthglen/Code Cache",
            "${APPDATA}/hearthglen/GPUCache",
            "${APPDATA}/hearthglen/DawnGraphiteCache",
            "${APPDATA}/hearthglen/DawnWebGPUCache",
            "${APPDATA}/hearthglen/Shared Dictionary/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-buzz-node-cache",
        "apps",
        "Buzz (Node)",
        "Caché de descargas y metadatos de npm de Buzz; conserva las herramientas y los módulos de Node instalados",
        &["${APPDATA}/Buzz/node-tools/cache"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-upscayl",
        "apps",
        "Upscayl",
        "Caché web, de código compilado, de GPU, de shaders y registros asentados de Upscayl; conserva las bases de datos de imágenes",
        &[
            "${APPDATA}/Upscayl/Cache/Cache_Data",
            "${APPDATA}/Upscayl/Code Cache",
            "${APPDATA}/Upscayl/GPUCache",
            "${APPDATA}/Upscayl/DawnCache",
            "${APPDATA}/Upscayl/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-todesktop-builder",
        "apps",
        "ToDesktop Builder",
        "Cachés web, de código compilado, de GPU, de shaders y de diccionario de ToDesktop Builder, y sus registros asentados; conserva proyectos, binarios, sesiones y almacenamiento",
        &[
            "${APPDATA}/ToDesktop Builder/Cache/Cache_Data",
            "${APPDATA}/ToDesktop Builder/Code Cache",
            "${APPDATA}/ToDesktop Builder/GPUCache",
            "${APPDATA}/ToDesktop Builder/DawnGraphiteCache",
            "${APPDATA}/ToDesktop Builder/DawnWebGPUCache",
            "${APPDATA}/ToDesktop Builder/Shared Dictionary/cache",
            "${APPDATA}/ToDesktop Builder/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-git-project-updater",
        "apps",
        "Git Project Updater",
        "Cachés web, de código compilado, de GPU, de shaders y de diccionario de Git Project Updater, y sus registros asentados; conserva repositorios y sesiones",
        &[
            "${APPDATA}/git-project-updater/Cache/Cache_Data",
            "${APPDATA}/git-project-updater/Code Cache",
            "${APPDATA}/git-project-updater/GPUCache",
            "${APPDATA}/git-project-updater/DawnGraphiteCache",
            "${APPDATA}/git-project-updater/DawnWebGPUCache",
            "${APPDATA}/git-project-updater/Shared Dictionary/cache",
            "${APPDATA}/git-project-updater/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-polyscope",
        "apps",
        "Polyscope",
        "Cachés web, de código compilado, de GPU, de shaders y de diccionario de Polyscope, y sus registros asentados; conserva el almacenamiento local, el estado de red y las sesiones",
        &[
            "${APPDATA}/Polyscope/Cache/Cache_Data",
            "${APPDATA}/Polyscope/Code Cache",
            "${APPDATA}/Polyscope/GPUCache",
            "${APPDATA}/Polyscope/DawnGraphiteCache",
            "${APPDATA}/Polyscope/DawnWebGPUCache",
            "${APPDATA}/Polyscope/Shared Dictionary/cache",
            "${APPDATA}/Polyscope/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-shure-plus-motiv",
        "apps",
        "ShurePlus MOTIV",
        "Cachés web, de código compilado y de GPU de ShurePlus MOTIV, y sus registros asentados; conserva el firmware, los ajustes del dispositivo y las grabaciones",
        &[
            "${APPDATA}/ShurePlus MOTIV/Cache/Cache_Data",
            "${APPDATA}/ShurePlus MOTIV/Code Cache",
            "${APPDATA}/ShurePlus MOTIV/GPUCache",
            "${APPDATA}/ShurePlus MOTIV/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-termius-beta",
        "apps",
        "Termius Beta",
        "Cachés web, de código compilado, de GPU y de shaders de Termius Beta, e informes de fallo antiguos; conserva credenciales, bases de datos, sesiones y almacenamiento",
        &[
            "${APPDATA}/Termius Beta/Cache/Cache_Data",
            "${APPDATA}/Termius Beta/Code Cache",
            "${APPDATA}/Termius Beta/GPUCache",
            "${APPDATA}/Termius Beta/DawnCache",
            "${APPDATA}/Termius Beta/Crashpad/reports",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-jetbrains-logs",
        "apps",
        "JetBrains (registros)",
        "Registros y salida de diagnóstico asentados de los IDE de JetBrains de más de una semana",
        &["${LOCALAPPDATA}/JetBrains/*/log"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    // Paquetes que dejan los actualizadores de las apps Electron en carpetas
    // `*-updater`. No se borra la carpeta: solo `installer.exe` y
    // `current.blockmap` sueltos, y solo si son antiguos. Si dentro hay un
    // `pending` hay una actualización a medias y no se toca NADA de esa carpeta.
    Regla {
        coincidencia_ficheros: Some(CoincidenciaFicheros {
            nombres: &["installer.exe", "current.blockmap"],
            sufijo_dir: Some("-updater"),
            dias_min: 14,
            saltar_si_existe: &["pending"],
        }),
        ..regla(
            "win-electron-updater-artifacts",
            "apps",
            "Electron (paquetes de actualización)",
            "Paquetes de actualización que las apps Electron dejan en carpetas `*-updater` (installer.exe y current.blockmap); solo se borran los ficheros sueltos de más de 14 días y nada de una carpeta que tenga una actualización a medias (`pending`)",
            &["${LOCALAPPDATA}"],
            TipoRegla::Contenido,
        )
    },
    // WebView2 es el navegador de Edge que llevan dentro muchas aplicaciones.
    // Cada una guarda su caché en una carpeta `EBWebView` anidada a profundidad
    // variable, así que se busca el ancla por las rutas que Kudu acota (no se
    // recorre todo `AppData\Local` a lo loco) y solo se borran las carpetas de
    // caché: cookies, sesiones, IndexedDB y almacenamiento local quedan intactos.
    Regla {
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "EBWebView",
            rutas_ancla: &[
                "*/EBWebView",
                "Microsoft/*/EBWebView",
                "Microsoft/*/*/EBWebView",
                "Microsoft/*/*/*/EBWebView",
                "Packages/*/*/EBWebView",
                "Packages/*/*/*/EBWebView",
                "Packages/*/*/*/*/EBWebView",
                "TeamViewer/EdgeBrowserControl/*/*/EBWebView",
                "TeamViewer/EdgeBrowserControl/*/*/*/EBWebView",
                "Zoom/data/WebviewCacheX64/*/EBWebView",
                "Google/DriveFS/webview2_user_data/*/EBWebView",
                "Microsoft/Office/*/Wef/webview2/*/*/EBWebView",
            ],
            objetivos: CACHES_DE_WEBVIEW2,
            ancestros_excluidos: RAMAS_DE_DATOS_WEBVIEW2,
            profundidad: 12,
        }),
        ..regla(
            "win-webview2",
            "apps",
            "WebView2 (cachés)",
            "Cachés web, de código compilado, de GPU y de shaders del motor WebView2 que muchas aplicaciones llevan embebido; conserva cookies, sesiones, IndexedDB, almacenamiento local y datos sin conexión",
            &["${LOCALAPPDATA}"],
            TipoRegla::Contenido,
        )
    },

    /* ── Herramientas de IA ───────────────────────────────────────────────── */
    regla(
        "win-cursor",
        "ia",
        "Cursor",
        "Caché de Cursor; conserva proyectos, historial de sesiones y ajustes",
        &[
            "${APPDATA}/Cursor/Cache/Cache_Data",
            "${APPDATA}/Cursor/Code Cache",
            "${APPDATA}/Cursor/GPUCache",
            "${APPDATA}/Cursor/CachedData",
            "${APPDATA}/Cursor/CachedExtensions",
            "${APPDATA}/Cursor/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Partitions",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-cursor-partitions",
            "ia",
            "Cursor (particiones)",
            "Cachés dentro de las particiones del navegador de Cursor; conserva las sesiones y los datos web persistentes (IndexedDB, almacenamiento local, service worker)",
            &["${APPDATA}/Cursor/Partitions"],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-windsurf",
        "ia",
        "Windsurf",
        "Caché de Windsurf; conserva proyectos, historial de sesiones y ajustes",
        &[
            "${APPDATA}/Windsurf/Cache/Cache_Data",
            "${APPDATA}/Windsurf/CachedData",
            "${APPDATA}/Windsurf/CachedExtensions",
            "${APPDATA}/Windsurf/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-claude",
        "ia",
        "Claude",
        "Cachés de Claude Desktop y Claude Code; NO toca conversaciones, proyectos, configuración, plugins ni copias de seguridad",
        &[
            "${APPDATA}/Claude/Cache/Cache_Data",
            "${APPDATA}/Claude/Code Cache",
            "${APPDATA}/Claude/GPUCache",
            "${APPDATA}/Claude/DawnGraphiteCache",
            "${APPDATA}/Claude/DawnWebGPUCache",
            "${APPDATA}/Claude/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/Code Cache",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/GPUCache",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/Shared Dictionary/cache",
            "${HOME}/.claude/cache",
            "${HOME}/.claude/plugins/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-claude-logs",
        "ia",
        "Claude (registros)",
        "Registros de diagnóstico de Claude de más de una semana; nunca toca conversaciones ni historial de ficheros",
        &[
            "${APPDATA}/Claude/logs",
            "${LOCALAPPDATA}/Claude/Logs",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Local/Claude/Logs",
            "${HOME}/.claude/debug",
            "${HOME}/.claude/logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Partitions",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-claude-partitions",
            "ia",
            "Claude (particiones)",
            "Cachés dentro de las particiones de las vistas previas de Claude; conserva las sesiones, IndexedDB, el almacenamiento local, los datos de service worker y el contenido sin conexión",
            &[
                "${APPDATA}/Claude/Partitions",
                "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/Partitions",
            ],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-codex",
        "ia",
        "Codex",
        "Cachés y ficheros temporales de Codex; conserva sesiones, memorias, credenciales y plugins",
        &["${HOME}/.codex/cache", "${HOME}/.codex/tmp"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-claude-crash-reports",
        "ia",
        "Claude (informes de fallo)",
        "Informes de fallo de Claude de más de una semana; conserva los ajustes del notificador y el estado pendiente",
        &[
            "${APPDATA}/Claude/Crashpad/reports",
            "${LOCALAPPDATA}/Packages/Claude_pzs8sxrjxfjjc/LocalCache/Roaming/Claude/Crashpad/reports",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-chatgpt-desktop-cache",
        "ia",
        "ChatGPT Desktop",
        "Caché web, de código compilado, de GPU, de shaders y de diccionario de ChatGPT Desktop; conserva el inicio de sesión, las conversaciones, IndexedDB, el almacenamiento local y las sesiones",
        &[
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/Code Cache",
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/GPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/Shared Dictionary/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Partitions",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-chatgpt-desktop-partitions",
            "ia",
            "ChatGPT Desktop (particiones)",
            "Cachés dentro de las particiones de ChatGPT Desktop; conserva las conversaciones, las sesiones, el almacenamiento y el contenido sin conexión",
            &["${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/Partitions"],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-chatgpt-desktop-logs",
        "ia",
        "ChatGPT Desktop (registros)",
        "Registros de diagnóstico de ChatGPT Desktop de más de una semana; las conversaciones y la cuenta no se tocan",
        &["${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Local/ChatGPT/Logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-chatgpt-desktop-crash-reports",
        "ia",
        "ChatGPT Desktop (informes de fallo)",
        "Informes de fallo de ChatGPT Desktop de más de una semana",
        &["${LOCALAPPDATA}/Packages/OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0/LocalCache/Roaming/ChatGPT/Crashpad/reports"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-codex-desktop-cache",
        "ia",
        "Codex Desktop",
        "Caché web, de código compilado, de GPU, de shaders, de componentes, de paquetes de extensiones y de diccionario de Codex Desktop; conserva conversaciones, perfiles del navegador, inicios de sesión, almacenamiento local, sesiones, plugins y entornos de ejecución",
        &[
            "${APPDATA}/Codex/Cache/Cache_Data",
            "${APPDATA}/Codex/Code Cache",
            "${APPDATA}/Codex/GPUCache",
            "${APPDATA}/Codex/DawnGraphiteCache",
            "${APPDATA}/Codex/DawnWebGPUCache",
            "${APPDATA}/Codex/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/Code Cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/GPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/Code Cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/GPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/Cache/Cache_Data",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/Code Cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/GPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/DawnGraphiteCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/DawnWebGPUCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/codex-browser-app/Shared Dictionary/cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/component_crx_cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/extensions_crx_cache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/GrShaderCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/ShaderCache",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/GPUPersistentCache/DawnGraphiteCache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Partitions",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-codex-desktop-partitions",
            "ia",
            "Codex Desktop (particiones)",
            "Cachés dentro de las particiones del navegador controlado de Codex Desktop; conserva extensiones, historial, descargas, inicios de sesión, sesiones, almacenamiento local, datos de service worker y contenido sin conexión",
            &["${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Default/Partitions"],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-codex-desktop-logs",
        "ia",
        "Codex Desktop (registros)",
        "Registros de diagnóstico de Codex Desktop de más de una semana; las bases de datos de tareas, estado, memoria y actividad no se tocan",
        &[
            "${APPDATA}/Codex/logs",
            "${LOCALAPPDATA}/Codex/Logs",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Local/Codex/Logs",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-codex-desktop-crash-reports",
        "ia",
        "Codex Desktop (informes de fallo)",
        "Informes de fallo de Codex Desktop de más de una semana",
        &[
            "${APPDATA}/Codex/Crashpad/reports",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/Crashpad/reports",
            "${LOCALAPPDATA}/Packages/OpenAI.Codex_2p2nqsd0c76g0/LocalCache/Roaming/Codex/web/Codex/Crashpad/reports",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-github-copilot-logs",
        "ia",
        "GitHub Copilot (registros)",
        "Registros de diagnóstico de GitHub Copilot de más de una semana; conserva las sesiones de chat y de edición, las credenciales y los datos del IDE",
        &["${HOME}/.copilot/logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-t3-code",
        "ia",
        "T3 Code",
        "Caché web, de código compilado, de GPU, de shaders y de diccionario de T3 Code; conserva espacios de trabajo y sesiones",
        &[
            "${APPDATA}/t3code/Cache/Cache_Data",
            "${APPDATA}/t3code/Code Cache",
            "${APPDATA}/t3code/GPUCache",
            "${APPDATA}/t3code/DawnGraphiteCache",
            "${APPDATA}/t3code/DawnWebGPUCache",
            "${APPDATA}/t3code/Shared Dictionary/cache",
        ],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    Regla {
        min_dias: 1,
        coincidencia_recursiva: Some(CoincidenciaRecursiva {
            ancla: "Partitions",
            rutas_ancla: &[],
            objetivos: CACHES_DE_PARTICION,
            ancestros_excluidos: RAMAS_DE_DATOS_PARTICION,
            profundidad: 8,
        }),
        ..regla(
            "win-t3-code-partitions",
            "ia",
            "T3 Code (particiones)",
            "Cachés dentro de las particiones de T3 Code; conserva las sesiones, el almacenamiento y los datos del espacio de trabajo de cada partición",
            &["${APPDATA}/t3code/Partitions"],
            TipoRegla::Contenido,
        )
    },
    regla(
        "win-t3-code-logs",
        "ia",
        "T3 Code (registros)",
        "Registros de diagnóstico de T3 Code de más de una semana; los adjuntos, los secretos y el estado del entorno no se tocan",
        &["${HOME}/.t3/userdata/logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),

    /* ── Gráfica ──────────────────────────────────────────────────────────── */
    regla(
        "win-nvidia",
        "gpu",
        "NVIDIA (shaders)",
        "Caché de shaders compilados de NVIDIA para OpenGL, DirectX y Vulkan; se rehace por juego, así que la primera vez irá más lenta",
        &[
            "${LOCALAPPDATA}/NVIDIA/GLCache",
            "${LOCALAPPDATA}/NVIDIA/DXCache",
            "${LOCALAPPDATA}/NVIDIA Corporation/NV_Cache",
            "${PROGRAMDATA}/NVIDIA Corporation/NV_Cache",
            "${HOME}/AppData/LocalLow/NVIDIA/DXCache",
            "${HOME}/AppData/LocalLow/NVIDIA/PerDriverVersion/DXCache",
        ],
        TipoRegla::Contenido,
    )
    .con_reinicio_cache(),
    regla(
        "win-amd-intel",
        "gpu",
        "AMD e Intel (shaders)",
        "Caché de shaders compilados de AMD e Intel para DirectX, OpenGL y Vulkan; se rehace por juego",
        &[
            "${LOCALAPPDATA}/AMD/DxCache",
            "${LOCALAPPDATA}/AMD/GLCache",
            "${LOCALAPPDATA}/AMD/VkCache",
            "${LOCALAPPDATA}/Intel/ShaderCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-unity-shaders",
        "gpu",
        "Unity (shaders)",
        "Caché de shaders compilados de Unity; se rehace al abrir los proyectos",
        &["${LOCALAPPDATA}/Unity/cache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-cuda",
        "gpu",
        "CUDA (kernels)",
        "Kernels compilados al vuelo por CUDA; se rehacen la próxima vez que se ejecuten",
        &["${APPDATA}/NVIDIA/ComputeCache"],
        TipoRegla::Contenido,
    ),

    /* ── Juegos ───────────────────────────────────────────────────────────── */
    regla(
        "win-steam",
        "juegos",
        "Steam",
        "Registros, volcados de fallo y caché web del cliente de Steam; se rehacen al abrirlo",
        &[
            "${PROGRAMFILES_X86}/Steam/logs",
            "${PROGRAMFILES_X86}/Steam/dumps",
            "${PROGRAMFILES_X86}/Steam/appcache/httpcache",
            "${LOCALAPPDATA}/Steam/htmlcache/Default/Cache",
            "${LOCALAPPDATA}/Steam/htmlcache/Default/Code Cache",
            "${LOCALAPPDATA}/Steam/htmlcache/Default/GPUCache",
            "${LOCALAPPDATA}/Steam/htmlcache/GrShaderCache",
            "${LOCALAPPDATA}/Steam/htmlcache/ShaderCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-steam-shaders",
        "juegos",
        "Steam (shaders por juego)",
        "Caché de shaders por juego de la biblioteca por defecto de Steam; se recompila al abrir cada juego",
        &["${PROGRAMFILES_X86}/Steam/steamapps/shadercache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-epic",
        "juegos",
        "Epic Games Launcher",
        "Caché web, registros, ficheros intermedios y caché de recursos Vault del lanzador de Epic; conserva los juegos instalados",
        &[
            "${LOCALAPPDATA}/EpicGamesLauncher/Saved/webcache",
            "${LOCALAPPDATA}/EpicGamesLauncher/Saved/webcache_4430",
            "${LOCALAPPDATA}/EpicGamesLauncher/Saved/Logs",
            "${LOCALAPPDATA}/EpicGamesLauncher/Intermediate",
            "${PROGRAMDATA}/Epic/EpicGamesLauncher/VaultCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-epic-webcache",
        "juegos",
        "Epic (caché web antigua)",
        "Caché web del lanzador de Epic de más de una semana; se rehace sola (cierra el lanzador antes de limpiar)",
        &["${LOCALAPPDATA}/EpicGamesLauncher/Saved/webcache_4147"],
        TipoRegla::Contenido,
    )
    .con_dias_como(7).con_recencia_profunda(),
    regla(
        "win-ea",
        "juegos",
        "EA App",
        "Registros y datos en caché de la EA App y del antiguo Origin; conserva los juegos instalados",
        &[
            "${LOCALAPPDATA}/Electronic Arts/EA Desktop/Logs",
            "${LOCALAPPDATA}/Electronic Arts/EA Desktop/IGOCache",
            "${LOCALAPPDATA}/EADesktop/cache",
            "${LOCALAPPDATA}/Origin/cache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-ea-logs",
        "juegos",
        "EA Desktop (registros)",
        "Registros asentados del servicio en segundo plano, el instalador y el escritorio de EA; los de menos de un día se conservan",
        &["${PROGRAMDATA}/EA Desktop/Logs"],
        TipoRegla::Contenido,
    )
    .con_dias_como(1).con_recencia_profunda(),
    regla(
        "win-ubisoft",
        "juegos",
        "Ubisoft Connect",
        "Caché web descargada y registros del cliente de Ubisoft Connect",
        &["${LOCALAPPDATA}/Ubisoft Game Launcher/cache", "${LOCALAPPDATA}/Ubisoft Game Launcher/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-battlenet",
        "juegos",
        "Battle.net",
        "Caché web y registros del lanzador de Battle.net",
        &[
            "${LOCALAPPDATA}/Battle.net/Cache",
            "${LOCALAPPDATA}/Blizzard Entertainment/Battle.net/Logs",
            "${APPDATA}/Battle.net/Logs",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-gog",
        "juegos",
        "GOG Galaxy",
        "Caché web y registros de GOG Galaxy",
        &[
            "${LOCALAPPDATA}/GOG.com/Galaxy/webcache",
            "${PROGRAMDATA}/GOG.com/Galaxy/logs",
            "${PROGRAMDATA}/GOG.com/Galaxy/webcache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-minecraft",
        "juegos",
        "Minecraft",
        "Registros, informes de fallo y caché del lanzador de Minecraft",
        &["${APPDATA}/.minecraft/logs", "${APPDATA}/.minecraft/crash-reports", "${APPDATA}/.minecraft/webcache2"],
        TipoRegla::Contenido,
    ),
    // Lanzadores y registros de juego que Kudu limpia y a nosotros nos faltaban.
    // Son registros y cachés que los propios juegos y lanzadores rehacen al
    // volver a abrirlos; no tocan partidas guardadas, cuentas ni ajustes.
    regla(
        "win-riot",
        "juegos",
        "Riot Games",
        "Registros del cliente de Riot Games (League of Legends, Valorant…); se rehacen al abrirlo",
        &["${LOCALAPPDATA}/Riot Games/Riot Client/Logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-xbox",
        "juegos",
        "Xbox",
        "Caché local de las aplicaciones Xbox y Xbox Gaming (paquetes de la Store); se rehace al abrirlas",
        &[
            "${LOCALAPPDATA}/Packages/Microsoft.GamingApp_8wekyb3d8bbwe/LocalCache",
            "${LOCALAPPDATA}/Packages/Microsoft.XboxApp_8wekyb3d8bbwe/LocalCache",
        ],
        TipoRegla::Contenido,
    ),
    regla(
        "win-rockstar",
        "juegos",
        "Rockstar Games Launcher",
        "Caché y registros del lanzador de Rockstar Games; conserva los juegos instalados",
        &["${LOCALAPPDATA}/Rockstar Games/Launcher/cache", "${LOCALAPPDATA}/Rockstar Games/Launcher/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-itch",
        "juegos",
        "itch.io",
        "Caché web y registros de la aplicación de itch.io; conserva los juegos instalados",
        &["${APPDATA}/itch/Cache/Cache_Data", "${APPDATA}/itch/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-roblox",
        "juegos",
        "Roblox",
        "Registros del reproductor de Roblox; se rehacen al volver a jugar",
        &["${LOCALAPPDATA}/Roblox/logs"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-valorant",
        "juegos",
        "Valorant",
        "Registros y volcados de fallo de Valorant; se rehacen al volver a jugar",
        &["${LOCALAPPDATA}/VALORANT/Saved/Logs", "${LOCALAPPDATA}/VALORANT/Saved/Crashes"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-fortnite",
        "juegos",
        "Fortnite",
        "Registros y volcados de fallo de Fortnite; se rehacen al volver a jugar",
        &["${LOCALAPPDATA}/FortniteGame/Saved/Logs", "${LOCALAPPDATA}/FortniteGame/Saved/Crashes"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-amazon-games",
        "juegos",
        "Amazon Games",
        "Registros y caché del navegador embebido del lanzador de Amazon Games; conserva los juegos instalados",
        &["${LOCALAPPDATA}/Amazon Games/Data/Logs", "${LOCALAPPDATA}/Amazon Games/App/CEFCache"],
        TipoRegla::Contenido,
    ),
    regla(
        "win-overwolf",
        "juegos",
        "Overwolf",
        "Registros y caché del navegador embebido de Overwolf (la superposición de CurseForge); los mods y los ajustes no se tocan",
        &["${LOCALAPPDATA}/Overwolf/Log", "${LOCALAPPDATA}/Overwolf/BrowserCache"],
        TipoRegla::Contenido,
    ),

    /* ── Privacidad (huellas) ─────────────────────────────────────────────── */
    // Estas NO son basura que se regenere sola: son huellas de TU actividad.
    // Borrarlas no lo vuelve a crear nadie, así que van marcadas con
    // `.marcar_traza()` y solo se limpian si se pide la categoría `privacidad`.
    regla(
        "win-hist-powershell",
        "privacidad",
        "Historial de PowerShell",
        "Las órdenes que has escrito en PowerShell. NO se recupera: si lo borras, se ha ido",
        &["${APPDATA}/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "win-recientes",
        "privacidad",
        "Elementos recientes",
        "Los accesos directos de los ficheros y carpetas que has abierto (lista de recientes del Explorador). NO se recupera",
        &["${APPDATA}/Microsoft/Windows/Recent/*.lnk"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "win-office-recientes",
        "privacidad",
        "Documentos recientes de Office",
        "Los accesos directos de los documentos recientes de Office. NO se recupera",
        &["${APPDATA}/Microsoft/Office/Recent/*.lnk"],
        TipoRegla::Fichero,
    )
    .marcar_traza(),
    regla(
        "win-jump-lists",
        "privacidad",
        "Listas de salto",
        "Las listas de salto de la barra de tareas: qué ficheros has abierto con cada aplicación. NO se recupera",
        &["${APPDATA}/Microsoft/Windows/Recent/AutomaticDestinations", "${APPDATA}/Microsoft/Windows/Recent/CustomDestinations"],
        TipoRegla::Contenido,
    )
    .marcar_traza(),
    regla(
        "win-portapapeles",
        "privacidad",
        "Historial del portapapeles",
        "El historial del portapapeles de Windows: lo que has copiado. NO se recupera",
        &["${LOCALAPPDATA}/Microsoft/Windows/Clipboard"],
        TipoRegla::Contenido,
    )
    .marcar_traza(),
    regla(
        "win-actividad",
        "privacidad",
        "Historial de actividad",
        "El historial de actividad de Windows (Timeline), qué abriste y cuándo, y el estado de sincronización entre dispositivos. NO se recupera",
        &["${LOCALAPPDATA}/ConnectedDevicesPlatform"],
        TipoRegla::Contenido,
    )
    .marcar_traza(),
];
